In [18]:
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from gamePredModel import GamePredModel, mdn_loss, players_and_stats
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

In [19]:
INPUT_DIM = 420
HIDDEN_DIM = 4096
OUTPUT_DIM = 180
N_COMPONENTS = 2
BATCH_SIZE = 32
GAME_ID = 22400367

In [ ]:




model = GamePredModel(input_dim=INPUT_DIM, hidden_dim=HIDDEN_DIM, output_dim=OUTPUT_DIM, n_components=N_COMPONENTS)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = mdn_loss
num_epochs = 3

df = pd.read_csv("../csv/masterGame.csv")

# Step 2: Split features and target
X = df.iloc[:, -420:]
y = df.iloc[:, 6:-420]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# # Step 4: To tensors
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

# Step 5: DataLoader
train_loader = DataLoader(
    TensorDataset(X_train_tensor, y_train_tensor), batch_size=BATCH_SIZE, shuffle=True
)
test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor), batch_size=BATCH_SIZE)
print(df.shape)
df.describe()

for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0
    epoch_start = time.time()

    for i, (batch_x, batch_y) in enumerate(train_loader, 1):
        batch_start = time.time()
        optimizer.zero_grad()

        # Forward pass
        pi, mu, sigma = model(batch_x)

        # Loss computation
        loss = mdn_loss(pi, mu, sigma, batch_y)
        total_loss += loss.item()

        # Backpropagation
        loss.backward()
        optimizer.step()

        batch_time = time.time() - batch_start
        if i % 100 == 0 or i == len(train_loader):
            print(
                f"Batch {i:3d}/{len(train_loader)} - Loss: {loss.item():.6f} - Time: {batch_time:.2f}s"
            )

    avg_train_loss = total_loss / len(train_loader)
    epoch_time = time.time() - epoch_start

    # ----- Evaluation -----
    model.eval()
    total_test_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in test_loader:
            pi, mu, sigma = model(batch_x)
            test_loss = mdn_loss(pi, mu, sigma, batch_y)
            total_test_loss += test_loss.item()

    avg_test_loss = total_test_loss / len(test_loader)

    # ----- Logging -----
    print(f"\nEpoch [{epoch+1}/{num_epochs}] Summary:")
    print(f"  Train Loss : {avg_train_loss:.6f}")
    print(f"  Test Loss  : {avg_test_loss:.6f}")
    print(f"  Epoch Time : {epoch_time:.2f}s")
    print("-" * 60)

(50646, 606)
Batch 100/1267 - Loss: 1.576847 - Time: 0.04s
Batch 200/1267 - Loss: 1.350944 - Time: 0.05s
Batch 300/1267 - Loss: 1.139496 - Time: 0.05s
Batch 400/1267 - Loss: 0.866256 - Time: 0.04s
Batch 500/1267 - Loss: 0.659202 - Time: 0.05s
Batch 600/1267 - Loss: 0.402075 - Time: 0.05s
Batch 700/1267 - Loss: 0.114194 - Time: 0.05s
Batch 800/1267 - Loss: -0.035770 - Time: 0.04s
Batch 900/1267 - Loss: -0.086494 - Time: 0.04s
Batch 1000/1267 - Loss: -0.119785 - Time: 0.04s
Batch 1100/1267 - Loss: -0.255725 - Time: 0.04s
Batch 1200/1267 - Loss: -0.385205 - Time: 0.04s
Batch 1267/1267 - Loss: -0.184323 - Time: 0.05s

Epoch [1/3] Summary:
  Train Loss : 0.532427
  Test Loss  : -0.324111
  Epoch Time : 61.31s
------------------------------------------------------------
Batch 100/1267 - Loss: -0.167822 - Time: 0.04s
Batch 200/1267 - Loss: -0.195944 - Time: 0.04s
Batch 300/1267 - Loss: -0.035185 - Time: 0.04s
Batch 400/1267 - Loss: 0.104692 - Time: 0.05s
Batch 500/1267 - Loss: -0.153475 - Time: 0.04s
Batch 600/1267 - Loss: -0.206626 - Time: 0.05s
Batch 700/1267 - Loss: -0.083815 - Time: 0.04s
Batch 800/1267 - Loss: -0.309171 - Time: 0.04s
Batch 900/1267 - Loss: -0.394617 - Time: 0.04s
Batch 1000/1267 - Loss: -0.349381 - Time: 0.04s
Batch 1100/1267 - Loss: -0.516831 - Time: 0.04s
Batch 1200/1267 - Loss: -0.494509 - Time: 0.04s
Batch 1267/1267 - Loss: -0.150718 - Time: 0.05s

Epoch [2/3] Summary:
  Train Loss : -0.265943
  Test Loss  : -0.188639
  Epoch Time : 54.37s
------------------------------------------------------------
Batch 100/1267 - Loss: -0.382872 - Time: 0.08s
Batch 200/1267 - Loss: -0.631778 - Time: 0.04s
Batch 300/1267 - Loss: -0.275608 - Time: 0.05s
Batch 400/1267 - Loss: -0.531447 - Time: 0.04s
Batch 500/1267 - Loss: -0.705301 - Time: 0.04s
Batch 600/1267 - Loss: -0.672879 - Time: 0.04s
Batch 700/1267 - Loss: -0.261133 - Time: 0.04s
Batch 800/1267 - Loss: -0.848603 - Time: 0.04s
Batch 900/1267 - Loss: -0.623595 - Time: 0.04s
Batch 1000/1267 - Loss: -0.751534 - Time: 0.04s
Batch 1100/1267 - Loss: -0.885601 - Time: 0.04s
Batch 1200/1267 - Loss: -0.664695 - Time: 0.04s
Batch 1267/1267 - Loss: -0.606324 - Time: 0.05s

Epoch [3/3] Summary:
  Train Loss : -0.523045
  Test Loss  : -0.151741
  Epoch Time : 54.15s
------------------------------------------------------------

In [35]:
# # After training
torch.save(model.state_dict(), "game_pred_mdn.pt")

In [36]:
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, "game_pred_mdn_full.pt")

In [37]:
model = GamePredModel(input_dim=INPUT_DIM, hidden_dim=HIDDEN_DIM, output_dim=OUTPUT_DIM, n_components=N_COMPONENTS)
model.load_state_dict(torch.load("game_pred_mdn.pt"))
model.eval()  # set to evaluation mode

checkpoint = torch.load("game_pred_mdn_full.pt")
model.load_state_dict(checkpoint["model_state_dict"])
optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

In [38]:
data = df[df["gameId"] == GAME_ID]
X_input = data.iloc[:, -420:]
data

,gameId,homeScore,awayScore,encodedHomeTeam,encodedAwayTeam,season,t0_p0_points,t0_p0_assists,t0_p0_blocks,t0_p0_steals,...,t1_p5_numMinutes,t1_p6_numMinutes,t1_p7_numMinutes,t1_p8_numMinutes,t1_p9_numMinutes,t1_p10_numMinutes,t1_p11_numMinutes,t1_p12_numMinutes,t1_p13_numMinutes,t1_p14_numMinutes
825,22400367,107,133,18,21,2024,17.0,7.0,1.0,3.0,...,27.48,18.46,18.15,5.05,4.06,1.5,0.0,0.0,0.0,0.0

In [39]:
X_tensor = torch.tensor(X_input.values, dtype=torch.float32)
X_tensor = X_tensor.view(1, -1)
print(X_tensor)
model.eval()  # if not already in eval mode
with torch.no_grad():
    pi, mu, sigma = model(X_tensor)

tensor([[3.6175e+01, 2.7212e+01, 4.4875e+00, 6.3750e-01, 1.1375e+00, 2.0150e+01,
         9.0125e+00, 1.0137e+01, 4.0000e+00, 6.2000e+00, 5.1875e+00, 5.6250e+00,
         3.1125e+00, 3.2061e+01, 1.8667e+01, 4.6812e+00, 2.3188e-01, 6.8116e-01,
         1.3609e+01, 6.5942e+00, 4.5507e+00, 1.5652e+00, 4.8551e+00, 3.9130e+00,
         7.0580e+00, 2.8406e+00, 2.5720e+01, 1.1476e+01, 3.5714e+00, 2.6984e-01,
         1.1587e+00, 9.4127e+00, 3.9683e+00, 6.9524e+00, 2.7619e+00, 1.0000e+00,
         7.7778e-01, 3.6190e+00, 1.5714e+00, 3.1675e+01, 1.2195e+01, 1.9878e+00,
         9.0244e-01, 1.3415e+00, 1.0171e+01, 4.8537e+00, 3.6951e+00, 1.2195e+00,
         1.5610e+00, 1.2683e+00, 5.7317e+00, 1.1585e+00, 3.2946e+01, 1.2028e+01,
         1.7639e+00, 1.4444e+00, 7.7778e-01, 7.0833e+00, 4.7361e+00, 0.0000e+00,
         0.0000e+00, 3.7917e+00, 2.5556e+00, 1.0903e+01, 1.2361e+00, 2.5079e+01,
         9.4268e+00, 2.7195e+00, 4.1463e-01, 6.0976e-01, 7.5122e+00, 3.2927e+00,
         4.5122e+00, 1.7195e+00, 1.4390e+00, 1.1220e+00, 3.2317e+00, 1.2073e+00,
         2.4520e+01, 8.0833e+00, 4.4306e+00, 1.9444e-01, 1.0972e+00, 6.5000e+00,
         2.5972e+00, 4.3056e+00, 1.7639e+00, 1.2500e+00, 1.1250e+00, 2.5278e+00,
         1.0417e+00, 1.0316e+01, 3.2206e+00, 1.4412e+00, 1.4706e-02, 2.9412e-01,
         3.1029e+00, 1.3676e+00, 1.0882e+00, 3.6765e-01, 2.2059e-01, 1.1765e-01,
         7.3529e-01, 7.7941e-01, 2.7263e+01, 1.4049e+01, 2.2346e+00, 8.8889e-01,
         7.1605e-01, 1.1395e+01, 5.2593e+00, 5.7037e+00, 2.1605e+00, 1.7654e+00,
         1.3704e+00, 5.9259e+00, 1.3333e+00, 1.0416e+01, 2.1562e+00, 5.0000e-01,
         7.8125e-02, 1.0938e-01, 1.7812e+00, 8.5938e-01, 4.8438e-01, 1.7188e-01,
         3.2812e-01, 2.6562e-01, 7.3438e-01, 2.3438e-01, 3.7056e+00, 2.3333e-01,
         1.6667e-01, 0.0000e+00, 3.3333e-02, 1.0000e-01, 6.6667e-02, 1.0000e-01,
         6.6667e-02, 2.0000e-01, 3.3333e-02, 1.6667e-01, 3.3333e-02, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 3.4752e+01, 2.2551e+01, 2.8462e+00,
         6.4103e-01, 9.1026e-01, 1.5577e+01, 8.1923e+00, 4.3333e+00, 1.8205e+00,
         5.2436e+00, 4.3462e+00, 1.1795e+01, 2.4615e+00, 3.6817e+01, 1.7610e+01,
         3.7317e+00, 5.2439e-01, 9.1463e-01, 1.4427e+01, 7.2195e+00, 5.6463e+00,
         2.0000e+00, 1.4390e+00, 1.1707e+00, 3.1585e+00, 1.6098e+00, 3.6359e+01,
         1.7299e+01, 2.1299e+00, 8.4416e-01, 1.4286e+00, 1.3338e+01, 6.3506e+00,
         5.9740e+00, 2.2208e+00, 2.9351e+00, 2.3766e+00, 4.6494e+00, 1.3247e+00,
         3.5175e+01, 2.4853e+01, 6.9853e+00, 1.1765e-01, 8.8235e-01, 1.7647e+01,
         8.6029e+00, 5.8382e+00, 2.2353e+00, 6.5882e+00, 5.4118e+00, 2.7500e+00,
         2.4118e+00, 2.4679e+01, 8.2568e+00, 2.5270e+00, 2.2973e-01, 9.0541e-01,
         7.3919e+00, 3.0000e+00, 4.2162e+00, 1.5541e+00, 8.6486e-01, 7.0270e-01,
         2.1757e+00, 5.5405e-01, 2.0318e+01, 6.2131e+00, 9.0164e-01, 6.8852e-01,
         7.7049e-01, 5.3607e+00, 2.6885e+00, 5.9016e-01, 1.6393e-01, 1.1311e+00,
         6.7213e-01, 5.1967e+00, 7.3770e-01, 1.4721e+01, 1.7895e+00, 5.7895e-01,
         4.7368e-01, 1.0526e-01, 1.3158e+00, 8.9474e-01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 3.5789e+00, 6.3158e-01, 1.4936e+01, 6.5789e+00,
         2.6711e+00, 2.1053e-01, 5.1316e-01, 5.8684e+00, 2.3553e+00, 3.3684e+00,
         1.2237e+00, 7.1053e-01, 6.4474e-01, 1.3684e+00, 6.8421e-01, 5.9950e+00,
         6.2500e-01, 1.0417e-01, 4.1667e-02, 6.2500e-02, 6.4583e-01, 2.0833e-01,
         3.9583e-01, 1.2500e-01, 1.2500e-01, 8.3333e-02, 3.7500e-01, 8.3333e-02,
         3.4047e+00, 5.3846e-01, 5.7692e-02, 0.0000e+00, 3.8462e-02, 5.9615e-01,
         1.9231e-01, 3.6538e-01, 1.1538e-01, 3.8462e-02, 3.8462e-02, 1.5385e-01,
         5.7692e-02, 8.5128e+00, 9.0566e-01, 2.0755e-01, 2.8302e-01, 1.8868e-02,
         5.8491e-01, 3.9623e-01, 0.0000e+00, 0.0000e+00, 2.4528e-01, 1.1321e-01,
         9.6226e-01, 3.9623e-01, 2.8475e+00, 1.2000e-01, 8.0000e-02, 0.0000e+00,
         4.0000e-02, 2.0000e-01, 6.0000e-02, 4.0000e-02, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 2.2000e-01, 4.0000e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         3.3350e+01, 3.0280e+01, 2.5280e+01, 2.4170e+01, 2.2180e+01, 2.2020e+01,
         1.8000e+01, 1.6320e+01, 1.5380e+01, 1.0340e+01, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 3.7380e+01, 3.5360e+01, 3.0250e+01,
         2.9450e+01, 2.8560e+01, 2.7480e+01, 1.8460e+01, 1.8150e+01, 5.0500e+00,
         4.0600e+00, 1.5000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [40]:
pi

tensor([[[7.1763e-06, 9.9999e-01],
         [3.9613e-01, 6.0387e-01],
         [5.6054e-01, 4.3946e-01],
         [4.5878e-01, 5.4122e-01],
         [4.5634e-01, 5.4366e-01],
         [3.2686e-01, 6.7314e-01],
         [9.9999e-01, 5.3950e-06],
         [3.7926e-01, 6.2074e-01],
         [4.2244e-01, 5.7756e-01],
         [5.2146e-01, 4.7854e-01],
         [6.0189e-01, 3.9811e-01],
         [6.3927e-01, 3.6073e-01],
         [2.6846e-04, 9.9973e-01],
         [6.4662e-01, 3.5338e-01],
         [9.9637e-01, 3.6296e-03],
         [4.0894e-01, 5.9106e-01],
         [3.8474e-01, 6.1526e-01],
         [8.9199e-01, 1.0801e-01],
         [3.0032e-03, 9.9700e-01],
         [3.0260e-01, 6.9740e-01],
         [3.4210e-01, 6.5790e-01],
         [4.2021e-01, 5.7979e-01],
         [4.6562e-01, 5.3438e-01],
         [3.3728e-01, 6.6272e-01],
         [9.9437e-01, 5.6279e-03],
         [3.9407e-01, 6.0593e-01],
         [3.6751e-01, 6.3249e-01],
         [6.2106e-01, 3.7894e-01],
         [5.8514e-01, 4.1486e-01],
         [4.9432e-01, 5.0568e-01],
         [7.7516e-01, 2.2484e-01],
         [5.4078e-01, 4.5922e-01],
         [6.9406e-01, 3.0594e-01],
         [2.8495e-02, 9.7151e-01],
         [5.1940e-01, 4.8060e-01],
         [5.2250e-01, 4.7750e-01],
         [2.3394e-01, 7.6606e-01],
         [5.5015e-01, 4.4985e-01],
         [2.7627e-01, 7.2373e-01],
         [9.9841e-01, 1.5942e-03],
         [5.9849e-01, 4.0151e-01],
         [9.9066e-01, 9.3436e-03],
         [1.2288e-01, 8.7712e-01],
         [6.4653e-01, 3.5347e-01],
         [7.7206e-01, 2.2794e-01],
         [2.9185e-03, 9.9708e-01],
         [8.2011e-01, 1.7989e-01],
         [4.2379e-01, 5.7621e-01],
         [2.7339e-01, 7.2661e-01],
         [4.9939e-01, 5.0061e-01],
         [1.4226e-01, 8.5774e-01],
         [7.9876e-01, 2.0124e-01],
         [2.1415e-01, 7.8585e-01],
         [4.1459e-01, 5.8541e-01],
         [6.3403e-03, 9.9366e-01],
         [6.6069e-01, 3.3931e-01],
         [9.1522e-01, 8.4777e-02],
         [5.1642e-02, 9.4836e-01],
         [6.2625e-01, 3.7375e-01],
         [1.5543e-03, 9.9845e-01],
         [7.6928e-02, 9.2307e-01],
         [9.6769e-01, 3.2309e-02],
         [9.8641e-01, 1.3593e-02],
         [1.6557e-03, 9.9834e-01],
         [7.8932e-02, 9.2107e-01],
         [4.4679e-02, 9.5532e-01],
         [9.9237e-01, 7.6268e-03],
         [4.9512e-03, 9.9505e-01],
         [4.9889e-03, 9.9501e-01],
         [9.9266e-01, 7.3432e-03],
         [9.9769e-01, 2.3056e-03],
         [9.9179e-01, 8.2095e-03],
         [6.3117e-03, 9.9369e-01],
         [7.9752e-03, 9.9202e-01],
         [1.3781e-02, 9.8622e-01],
         [9.9054e-01, 9.4618e-03],
         [1.5311e-02, 9.8469e-01],
         [9.9687e-01, 3.1303e-03],
         [5.3180e-03, 9.9468e-01],
         [1.3601e-02, 9.8640e-01],
         [9.9907e-01, 9.3160e-04],
         [9.8613e-01, 1.3866e-02],
         [9.7988e-01, 2.0115e-02],
         [9.9824e-01, 1.7573e-03],
         [1.3178e-02, 9.8682e-01],
         [9.9590e-01, 4.0977e-03],
         [9.3755e-01, 6.2453e-02],
         [4.3776e-03, 9.9562e-01],
         [9.9797e-01, 2.0315e-03],
         [6.4532e-03, 9.9355e-01],
         [9.9998e-01, 1.5423e-05],
         [5.9099e-01, 4.0901e-01],
         [3.9012e-01, 6.0988e-01],
         [4.9839e-01, 5.0161e-01],
         [4.7679e-01, 5.2321e-01],
         [3.7757e-01, 6.2243e-01],
         [9.9994e-01, 6.1470e-05],
         [3.5585e-01, 6.4415e-01],
         [5.0559e-03, 9.9494e-01],
         [5.9856e-01, 4.0144e-01],
         [5.9120e-01, 4.0880e-01],
         [3.8188e-01, 6.1812e-01],
         [9.9990e-01, 9.6325e-05],
         [3.3922e-01, 6.6078e-01],
         [6.6288e-01, 3.3712e-01],
         [6.5442e-01, 3.4558e-01],
         [6.1180e-01, 3.8820e-01],
         [3.7276e-01, 6.2724e-01],
         [9.9995e-01, 5.1310e-05],
         [6.5814e-01, 3.4186e-01],
         [3.5427e-01, 6.4573e-01],
         [3.8971e-01, 6.1029e-01],
         [6.2290e-01, 3.7710e-01],
         [5.7504e-01, 4.2496e-01],
         [8.2325e-01, 1.7675e-01],
         [5.9652e-01, 4.0348e-01],
         [3.1452e-01, 6.8548e-01],
         [5.3861e-01, 4.6139e-01],
         [5.9005e-01, 4.0995e-01],
         [4.5612e-01, 5.4388e-01],
         [7.5100e-01, 2.4900e-01],
         [6.2124e-01, 3.7876e-01],
         [3.7793e-01, 6.2207e-01],
         [5.4238e-01, 4.5762e-01],
         [4.4843e-01, 5.5157e-01],
         [5.1568e-01, 4.8432e-01],
         [9.4708e-01, 5.2916e-02],
         [5.3147e-01, 4.6853e-01],
         [2.4142e-01, 7.5858e-01],
         [3.6341e-01, 6.3659e-01],
         [4.5577e-01, 5.4423e-01],
         [3.5290e-01, 6.4710e-01],
         [8.6147e-01, 1.3853e-01],
         [4.8243e-01, 5.1757e-01],
         [8.3934e-01, 1.6066e-01],
         [7.1057e-01, 2.8943e-01],
         [7.2381e-01, 2.7619e-01],
         [9.7232e-01, 2.7680e-02],
         [4.1757e-01, 5.8243e-01],
         [3.0312e-01, 6.9688e-01],
         [1.0643e-01, 8.9357e-01],
         [9.9918e-01, 8.1790e-04],
         [8.9098e-01, 1.0902e-01],
         [6.5067e-01, 3.4933e-01],
         [7.8123e-01, 2.1877e-01],
         [9.8421e-01, 1.5787e-02],
         [2.4555e-02, 9.7545e-01],
         [9.4800e-01, 5.2001e-02],
         [9.9907e-01, 9.3071e-04],
         [1.1678e-01, 8.8322e-01],
         [6.6243e-02, 9.3376e-01],
         [3.1929e-02, 9.6807e-01],
         [1.1723e-02, 9.8828e-01],
         [9.8843e-01, 1.1566e-02],
         [9.3888e-01, 6.1120e-02],
         [9.7171e-01, 2.8295e-02],
         [9.8902e-01, 1.0976e-02],
         [2.5418e-03, 9.9746e-01],
         [9.9331e-01, 6.6890e-03],
         [7.5310e-03, 9.9247e-01],
         [9.9223e-01, 7.7683e-03],
         [9.9452e-01, 5.4786e-03],
         [9.9619e-01, 3.8066e-03],
         [6.6927e-03, 9.9331e-01],
         [8.0668e-03, 9.9193e-01],
         [3.7414e-03, 9.9626e-01],
         [9.9446e-01, 5.5398e-03],
         [9.8136e-01, 1.8639e-02],
         [9.9607e-01, 3.9340e-03],
         [3.2726e-03, 9.9673e-01],
         [1.7747e-02, 9.8225e-01],
         [9.8322e-01, 1.6775e-02],
         [5.6320e-03, 9.9437e-01],
         [8.1688e-03, 9.9183e-01],
         [6.2927e-04, 9.9937e-01],
         [9.8787e-01, 1.2128e-02],
         [9.9733e-01, 2.6684e-03],
         [9.9835e-01, 1.6523e-03],
         [9.7662e-01, 2.3378e-02],
         [9.7616e-01, 2.3841e-02]]])

In [41]:
mu

tensor([[[ 9.3392e-01,  2.4105e+01],
         [ 9.2901e+00,  3.4338e+00],
         [-3.4583e-03,  2.1413e+00],
         [ 2.6972e+00,  5.6770e-01],
         [ 5.0958e+00,  1.1326e+01],
         [ 4.7558e+00,  1.9777e+00],
         [ 2.1205e+01,  9.6345e-02],
         [ 8.5239e+00,  2.9930e+00],
         [ 2.0905e+00, -1.1427e-02],
         [ 5.2645e-01,  2.6619e+00],
         [ 4.9966e+00,  1.1240e+01],
         [ 1.5770e+00,  4.2139e+00],
         [-3.7592e-02,  1.8001e+01],
         [ 2.2775e+00,  7.3075e+00],
         [ 8.2927e-01, -2.4498e-01],
         [ 2.4286e+00,  5.3953e-01],
         [ 1.0561e+01,  4.5402e+00],
         [ 2.4279e+00,  1.2399e+00],
         [ 2.6075e+00,  1.4708e+01],
         [ 6.3290e+00,  1.9878e+00],
         [ 2.8517e-03,  1.5308e+00],
         [-6.2398e-03,  1.9299e+00],
         [ 9.4819e+00,  3.8662e+00],
         [ 3.3069e+00,  1.0229e+00],
         [ 1.2020e+01,  2.4735e+00],
         [ 5.0599e+00,  1.4134e+00],
         [ 1.8892e+00,  1.2424e-03],
         [ 1.8086e+00, -4.1720e-03],
         [ 3.4270e+00,  8.6297e+00],
         [ 2.6427e+00,  6.1717e-01],
         [ 1.2486e+01,  5.6682e+00],
         [ 1.0972e+00,  4.1923e+00],
         [ 2.2860e-03,  1.8141e+00],
         [-1.2692e-02,  1.0278e+00],
         [ 2.7671e+00,  7.4361e+00],
         [ 5.6925e-01,  2.5536e+00],
         [ 3.1922e+00,  9.9168e+00],
         [ 3.2605e+00,  6.8842e-01],
         [ 1.6778e+00, -1.9839e-04],
         [ 7.2049e-01, -1.7252e-01],
         [ 5.7484e+00,  1.9901e+00],
         [ 1.1687e+00,  1.0677e-01],
         [-2.4201e-02,  6.4501e+00],
         [ 2.3536e+00, -6.6907e-03],
         [-1.4989e-02,  1.6039e+00],
         [ 1.1066e-01,  4.7835e-01],
         [ 4.0108e+00,  7.6397e-01],
         [ 1.0012e-02,  1.8728e+00],
         [ 9.4057e-03,  5.2546e+00],
         [ 2.0225e+00, -6.9826e-03],
         [ 1.4328e+00,  1.8647e-03],
         [ 8.3034e-03,  1.4388e+00],
         [-1.1309e-02,  2.9031e+00],
         [ 1.6766e+00,  3.5094e-03],
         [-1.7489e-01,  1.5472e+00],
         [-7.5424e-03,  6.1330e-01],
         [-1.6520e-02,  7.8911e-01],
         [ 9.5484e-01, -2.4199e-03],
         [-2.0017e-03,  2.2286e+00],
         [-1.3576e-01,  3.5265e-01],
         [ 3.5613e+00,  6.7490e-04],
         [ 8.9470e-03,  1.1262e+00],
         [-1.2592e-02,  4.7975e-01],
         [ 2.8693e-01,  4.5845e-02],
         [ 1.4133e+00,  1.6081e-02],
         [ 7.3621e-01, -1.1616e-03],
         [-7.7130e-03,  2.2823e+00],
         [ 4.6471e-01, -8.8843e-03],
         [ 1.1218e-01, -4.6029e-03],
         [ 7.6919e-03,  1.3183e-01],
         [ 3.0434e-02,  9.5682e-02],
         [-1.1145e-02,  3.2984e-01],
         [ 2.8476e-01,  4.2567e-03],
         [ 7.5863e-02,  1.9776e-02],
         [ 2.1728e-02, -9.8443e-03],
         [-2.1114e-03,  9.4150e-04],
         [ 1.8624e-02, -5.3704e-03],
         [ 1.3458e-03,  4.8563e-02],
         [ 6.3898e-02,  2.1508e-03],
         [-7.9217e-04,  3.5690e-03],
         [ 1.5495e-02, -5.9845e-02],
         [-3.3784e-03,  8.7711e-03],
         [-1.0554e-04,  4.5216e-02],
         [-7.1742e-03,  6.4615e-01],
         [ 6.5507e-02, -1.9193e-02],
         [-7.2825e-03,  1.0788e-02],
         [-1.1054e-02, -1.3847e-02],
         [ 1.2727e-02, -2.7808e-03],
         [ 1.2548e-03,  1.5631e-01],
         [ 5.4437e-03,  5.9178e-04],
         [ 2.3412e+01,  4.5580e-01],
         [ 3.1593e+00,  8.5239e+00],
         [ 1.8242e+00,  1.9551e-02],
         [ 5.5788e-01,  2.5562e+00],
         [ 1.1585e+01,  5.1955e+00],
         [ 4.8369e+00,  1.9538e+00],
         [ 1.9292e+01, -1.8372e-02],
         [ 7.6839e+00,  2.5197e+00],
         [ 9.0472e-02,  8.1862e-01],
         [ 5.8158e-01,  2.5009e+00],
         [ 4.4598e+00,  1.0727e+01],
         [ 4.3148e+00,  1.6229e+00],
         [ 1.6791e+01,  1.9818e-01],
         [ 6.8229e+00,  1.9595e+00],
         [ 3.4721e-03,  1.8227e+00],
         [ 5.3719e-01,  2.4373e+00],
         [ 4.2926e+00,  1.0049e+01],
         [ 3.9597e+00,  1.2952e+00],
         [ 1.4314e+01,  2.4617e-01],
         [ 1.6670e+00,  5.7209e+00],
         [ 1.7644e+00, -8.9452e-03],
         [-1.0478e-03,  1.8171e+00],
         [ 3.8445e+00,  9.2055e+00],
         [ 1.0682e+00,  3.4325e+00],
         [ 1.3438e+01,  6.1335e+00],
         [ 1.1982e+00,  4.5871e+00],
         [ 1.6912e+00,  2.0611e-03],
         [ 1.8131e+00, -6.6531e-03],
         [ 3.2107e+00,  8.0124e+00],
         [ 6.2887e-01,  2.8231e+00],
         [ 1.1225e+01,  4.6141e+00],
         [ 9.1524e-01,  3.7332e+00],
         [-6.6853e-02,  9.8662e-01],
         [-1.8808e-04,  1.7037e+00],
         [ 7.0325e+00,  2.6744e+00],
         [ 2.5210e+00,  5.4754e-01],
         [ 7.6824e+00, -2.3087e-03],
         [ 5.2774e-01,  3.0019e+00],
         [ 1.5434e+00, -2.5149e-03],
         [ 1.6212e+00,  1.8039e-03],
         [ 1.6965e+00,  5.5452e+00],
         [ 2.6306e-02,  1.9541e+00],
         [ 6.2849e+00,  1.2073e-02],
         [ 2.3270e-03,  2.2658e+00],
         [ 4.8880e-03,  1.4299e+00],
         [ 1.1483e-02,  1.3435e+00],
         [ 3.8220e+00,  6.7659e-01],
         [ 8.0094e-01, -7.8912e-02],
         [-1.0030e-02,  5.1392e+00],
         [ 1.9147e+00,  8.8047e-03],
         [ 9.7070e-01,  3.6472e-03],
         [ 2.6857e-01, -2.1727e-01],
         [ 2.1877e+00,  1.0474e-01],
         [-1.2625e-02,  1.4996e+00],
         [-3.6330e-03,  4.1257e+00],
         [ 2.4268e-01,  1.7909e-01],
         [ 8.6163e-01,  9.4322e-03],
         [-9.7471e-03,  1.0941e+00],
         [ 6.3493e-01,  2.2374e-01],
         [ 1.3537e+00, -1.6457e-03],
         [ 3.2076e+00, -4.4642e-03],
         [ 5.7749e-01,  6.4707e-03],
         [ 5.2298e-01, -1.4126e-02],
         [ 1.4799e-02,  6.7057e-01],
         [ 2.3919e-03,  1.6023e+00],
         [-2.3924e-03,  1.1359e+00],
         [-2.4093e-03,  1.8347e+00],
         [-8.6996e-02, -4.7856e-03],
         [-1.8785e-02,  4.7877e-02],
         [ 1.6815e-01,  1.0391e-03],
         [-1.6164e-02,  1.0595e+00],
         [-7.9110e-03,  3.1845e-01],
         [ 7.4812e-03,  4.1415e-01],
         [ 8.3044e-02, -5.4930e-03],
         [ 4.8361e-03,  2.0812e-03],
         [-2.5067e-01, -4.4141e-03],
         [ 5.9175e-03, -5.3300e-02],
         [ 8.2808e-03,  2.0706e-02],
         [ 9.0559e-03, -7.8300e-02],
         [-2.0754e-01,  6.4196e-03],
         [ 8.1306e-02, -1.2167e-02],
         [-5.2848e-03, -7.3968e-03],
         [-4.6135e-03, -1.7973e-03],
         [ 4.5740e-03, -9.4324e-03],
         [ 1.5781e-01, -2.0815e-03],
         [-5.3848e-03, -8.1901e-03],
         [-2.9539e-03,  2.1000e-01],
         [-9.0863e-04, -7.5425e-03],
         [-9.0258e-03, -4.7860e-03],
         [ 1.5734e-03, -3.0902e-03]]])

In [42]:
sigma

tensor([[[9.9300e-01, 9.7993e+00],
         [4.6272e+00, 1.9293e+00],
         [1.7291e-03, 1.4370e+00],
         [1.4585e+00, 5.1846e-01],
         [2.1779e+00, 5.4048e+00],
         [2.1973e+00, 1.2611e+00],
         [9.4364e+00, 3.1460e-01],
         [4.3531e+00, 1.8724e+00],
         [1.3410e+00, 2.7173e-03],
         [5.0848e-01, 1.4367e+00],
         [2.4180e+00, 5.1049e+00],
         [1.0059e+00, 1.9696e+00],
         [2.4034e-02, 8.4651e+00],
         [1.4736e+00, 3.8498e+00],
         [1.2010e+00, 4.9053e-03],
         [1.3284e+00, 4.8207e-01],
         [4.6913e+00, 2.3178e+00],
         [1.9447e+00, 5.7535e-02],
         [1.0366e-01, 7.6891e+00],
         [3.4850e+00, 1.3618e+00],
         [3.1701e-03, 1.3053e+00],
         [2.4135e-03, 9.8897e-01],
         [4.4101e+00, 2.1236e+00],
         [1.7788e+00, 8.0253e-01],
         [6.7016e+00, 1.4849e-01],
         [2.8788e+00, 9.7753e-01],
         [1.1968e+00, 1.7753e-03],
         [1.0416e+00, 1.7552e-03],
         [1.7545e+00, 3.8990e+00],
         [1.4774e+00, 5.0999e-01],
         [5.9136e+00, 3.0077e+00],
         [8.4625e-01, 2.5210e+00],
         [1.7250e-03, 1.0332e+00],
         [3.0256e-03, 1.0334e+00],
         [1.5464e+00, 3.4848e+00],
         [4.9865e-01, 1.3111e+00],
         [2.1860e+00, 5.1473e+00],
         [1.9671e+00, 5.7545e-01],
         [9.3057e-01, 2.0565e-03],
         [8.0957e-01, 4.1754e-02],
         [2.8143e+00, 1.1652e+00],
         [1.1338e+00, 2.8407e-03],
         [4.3520e-03, 4.2166e+00],
         [1.4673e+00, 2.2771e-03],
         [1.6305e-03, 8.6706e-01],
         [3.8996e-03, 6.0014e-01],
         [2.4614e+00, 5.4364e-01],
         [1.8018e-03, 8.9756e-01],
         [2.0881e-03, 3.5526e+00],
         [1.3140e+00, 2.0377e-03],
         [7.3131e-01, 1.7042e-03],
         [2.1590e-03, 6.8396e-01],
         [2.0632e-03, 1.8716e+00],
         [7.7511e-01, 1.8401e-03],
         [5.0721e-03, 1.9850e+00],
         [3.3413e-03, 1.1175e+00],
         [2.0079e-03, 7.8600e-01],
         [7.2611e-01, 2.6788e-03],
         [1.8986e-03, 1.5897e+00],
         [6.4789e-03, 4.8577e-01],
         [2.6851e+00, 1.4498e-03],
         [1.7031e-03, 9.4984e-01],
         [2.0157e-03, 6.0338e-01],
         [4.4411e-03, 9.5522e-02],
         [1.3650e+00, 1.4866e-03],
         [8.2700e-01, 3.2917e-03],
         [1.6359e-03, 2.6038e+00],
         [7.5141e-01, 1.9081e-03],
         [3.0893e-01, 1.4691e-03],
         [1.6856e-03, 2.7333e-01],
         [9.3253e-02, 2.7506e-03],
         [2.0588e-03, 5.8410e-01],
         [1.0802e+00, 1.6096e-03],
         [1.1246e-01, 1.5315e-03],
         [1.4422e-01, 2.3035e-03],
         [1.9902e-03, 7.0735e-02],
         [1.1005e-01, 2.0866e-03],
         [2.7772e-03, 2.1788e-01],
         [6.5879e-01, 1.8160e-03],
         [3.0721e-02, 2.1870e-03],
         [2.8802e-03, 4.3510e-02],
         [1.9492e-03, 1.2153e-01],
         [2.6484e-03, 8.9922e-02],
         [4.6624e-03, 1.2340e-02],
         [3.7168e-02, 1.5124e-03],
         [1.7883e-03, 7.7681e-02],
         [1.8073e-03, 8.5875e-03],
         [3.1485e-01, 1.6765e-03],
         [5.1370e-03, 2.9675e-03],
         [9.0005e-02, 2.0963e-03],
         [9.6994e+00, 6.6285e-01],
         [1.7983e+00, 4.2098e+00],
         [1.2027e+00, 2.7837e-03],
         [4.8653e-01, 1.3065e+00],
         [5.2576e+00, 2.3862e+00],
         [2.1066e+00, 1.1768e+00],
         [8.6413e+00, 2.6934e-01],
         [3.9128e+00, 1.6590e+00],
         [4.6979e-03, 1.1519e+00],
         [4.9224e-01, 1.3413e+00],
         [2.2795e+00, 4.9480e+00],
         [2.0238e+00, 1.0393e+00],
         [8.1755e+00, 5.5000e-01],
         [3.6053e+00, 1.3587e+00],
         [1.6582e-03, 1.2075e+00],
         [4.6950e-01, 1.3048e+00],
         [2.1174e+00, 4.6010e+00],
         [1.8793e+00, 9.1295e-01],
         [7.7382e+00, 5.2806e-01],
         [1.2206e+00, 3.0929e+00],
         [1.1129e+00, 1.5443e-03],
         [2.5423e-03, 8.6801e-01],
         [2.0285e+00, 4.2884e+00],
         [8.4488e-01, 1.7482e+00],
         [6.6395e+00, 3.0397e+00],
         [9.0014e-01, 2.7097e+00],
         [9.6661e-01, 2.0862e-03],
         [8.7220e-01, 2.8319e-03],
         [1.7990e+00, 3.9133e+00],
         [5.5496e-01, 1.4779e+00],
         [5.7091e+00, 2.6881e+00],
         [7.1684e-01, 2.2173e+00],
         [2.5591e-03, 9.4881e-01],
         [2.0304e-03, 8.3675e-01],
         [3.3298e+00, 1.5442e+00],
         [1.2788e+00, 4.9020e-01],
         [4.7619e+00, 3.4289e-03],
         [4.9003e-01, 1.9222e+00],
         [7.7958e-01, 1.7588e-03],
         [7.4334e-01, 1.8260e-03],
         [1.1463e+00, 2.8042e+00],
         [2.0277e-03, 1.0382e+00],
         [4.0182e+00, 1.9541e-03],
         [1.6086e-03, 1.3583e+00],
         [2.1784e-03, 8.1691e-01],
         [1.7502e-03, 7.0624e-01],
         [2.3207e+00, 5.2142e-01],
         [9.5746e-01, 3.5521e-03],
         [1.7393e-03, 3.3104e+00],
         [1.2042e+00, 1.7608e-03],
         [5.9993e-01, 3.7731e-03],
         [4.3843e-01, 2.2107e-02],
         [1.9469e+00, 2.1515e-03],
         [2.3628e-03, 8.1982e-01],
         [1.8865e-03, 2.7925e+00],
         [5.3911e-01, 2.1927e-03],
         [3.7328e-01, 3.3182e-03],
         [1.7383e-03, 6.9261e-01],
         [8.2177e-01, 4.1001e-02],
         [6.7079e-01, 1.3562e-03],
         [2.6158e+00, 1.9935e-03],
         [6.3247e-01, 2.1125e-03],
         [6.3671e-01, 1.5853e-03],
         [1.7933e-03, 7.0482e-01],
         [2.0363e-03, 1.3003e+00],
         [2.5754e-03, 8.2485e-01],
         [3.1917e-03, 2.5056e+00],
         [5.4856e-01, 4.4619e-03],
         [1.4402e-03, 2.2957e-01],
         [4.2856e-01, 1.4292e-03],
         [1.7274e-03, 1.2565e+00],
         [2.1811e-03, 5.7659e-01],
         [2.0385e-03, 1.3133e+00],
         [3.4637e-01, 2.4620e-03],
         [8.9879e-02, 1.5674e-03],
         [2.8623e-01, 1.8680e-03],
         [3.7670e-03, 2.2836e-01],
         [2.4016e-03, 9.3005e-02],
         [2.5455e-03, 1.4162e-01],
         [3.2421e-01, 1.9410e-03],
         [2.8281e-03, 3.2284e-02],
         [1.8322e-03, 6.5475e-02],
         [7.7445e-02, 1.9675e-03],
         [5.9285e-02, 1.6263e-03],
         [2.7284e-02, 2.9151e-03],
         [1.4191e-03, 4.5182e-02],
         [1.4412e-03, 4.2445e-01],
         [1.7561e-03, 7.0752e-02],
         [1.7871e-03, 1.5574e-02],
         [2.0927e-03, 2.7014e-02]]])

In [43]:
def sample_from_mdn(pi, mu, sigma):
    """
    pi:    (B, D, K) — mixture weights
    mu:    (B, D, K) — means
    sigma: (B, D, K) — stds

    Returns:
        samples: (B, D)
    """
    B, D, K = pi.shape

    # Step 1: Sample a component index from categorical distribution for each output dim
    categorical = torch.distributions.Categorical(pi)
    component_indices = categorical.sample()  # (B, D) — mixture component chosen per output

    # Step 2: Gather mu and sigma corresponding to sampled component
    batch_indices = torch.arange(B).unsqueeze(1).expand(B, D)  # (B, D)
    dim_indices = torch.arange(D).unsqueeze(0).expand(B, D)    # (B, D)

    # Gather the corresponding mu and sigma based on sampled component
    chosen_mu = mu[batch_indices, dim_indices, component_indices]
    chosen_sigma = sigma[batch_indices, dim_indices, component_indices]

    # Step 3: Sample from normal distribution
    normal = torch.distributions.Normal(chosen_mu, chosen_sigma)
    samples = normal.sample()  # (B, D)
    samples = torch.clamp(samples, min=0.0)

    return samples

In [199]:
samples = sample_from_mdn(pi, mu, sigma)  # Shape: (1, 360)

In [200]:
h, a = players_and_stats(samples, GAME_ID, "../csv/masterGame.csv", "../csv/PlayerStatistics.csv")

Schema({'firstName': String, 'lastName': String, 'personId': Int64, 'gameId': Int64, 'gameDate': String, 'playerteamCity': String, 'playerteamName': String, 'opponentteamCity': String, 'opponentteamName': String, 'gameType': String, 'gameLabel': String, 'gameSubLabel': String, 'seriesGameNumber': Float64, 'win': Int64, 'home': Int64, 'numMinutes': Float64, 'points': Float64, 'assists': Float64, 'blocks': Float64, 'steals': Float64, 'fieldGoalsAttempted': Float64, 'fieldGoalsMade': Float64, 'fieldGoalsPercentage': Float64, 'threePointersAttempted': Float64, 'threePointersMade': Float64, 'threePointersPercentage': Float64, 'freeThrowsAttempted': Float64, 'freeThrowsMade': Float64, 'freeThrowsPercentage': Float64, 'reboundsDefensive': Float64, 'reboundsOffensive': Float64, 'reboundsTotal': Float64, 'foulsPersonal': Float64, 'turnovers': Float64, 'plusMinusPoints': Float64, 'encodedTeam': Int64})
18 21

In [201]:
print(h["points"].sum(), a["points"].sum())

117.1013412475586 140.3069610595703

In [202]:
h

shape: (15, 9)
┌───────────┬────────────┬──────────┬───────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ firstName ┆ lastName   ┆ personId ┆ points    ┆ … ┆ blocks   ┆ steals   ┆ reboundsTo ┆ turnovers │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ tal        ┆ ---       │
│ str       ┆ str        ┆ i64      ┆ f32       ┆   ┆ f32      ┆ f32      ┆ ---        ┆ f32       │
│           ┆            ┆          ┆           ┆   ┆          ┆          ┆ f32        ┆           │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ Anthony   ┆ Edwards    ┆ 1630162  ┆ 25.803543 ┆ … ┆ 0.0      ┆ 0.947284 ┆ 9.076491   ┆ 1.751937  │
│ Julius    ┆ Randle     ┆ 203944   ┆ 39.267982 ┆ … ┆ 0.224781 ┆ 0.830468 ┆ 9.787584   ┆ 0.767914  │
│ Donte     ┆ DiVincenzo ┆ 1628978  ┆ 10.460669 ┆ … ┆ 0.0      ┆ 0.792567 ┆ 2.908532   ┆ 0.939958  │
│ Jaden     ┆ McDaniels  ┆ 1630183  ┆ 6.931751  ┆ … ┆ 0.010324 ┆ 0.0      ┆ 11.6703    ┆ 2.813545  │
│ Rudy      ┆ Gobert     ┆ 203497   ┆ 11.035434 ┆ … ┆ 0.003017 ┆ 2.051392 ┆ 4.685094   ┆ 4.405427  │
│ …         ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ Luka      ┆ Garza      ┆ 1630568  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.014725   ┆ 0.0       │
│ Josh      ┆ Minott     ┆ 1631169  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.007492 ┆ 0.0        ┆ 0.0       │
│ PJ        ┆ Dozier     ┆ 1628408  ┆ 0.003239  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.004313  │
│ null      ┆ null       ┆ null     ┆ 0.000559  ┆ … ┆ 0.018026 ┆ 0.0      ┆ 0.001782   ┆ 0.0       │
│ null      ┆ null       ┆ null     ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.000343 ┆ 0.0        ┆ 0.000011  │
└───────────┴────────────┴──────────┴───────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [203]:
a

shape: (15, 9)
┌─────────────┬──────────┬──────────┬───────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ firstName   ┆ lastName ┆ personId ┆ points    ┆ … ┆ blocks   ┆ steals   ┆ reboundsTo ┆ turnovers │
│ ---         ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ tal        ┆ ---       │
│ str         ┆ str      ┆ i64      ┆ f32       ┆   ┆ f32      ┆ f32      ┆ ---        ┆ f32       │
│             ┆          ┆          ┆           ┆   ┆          ┆          ┆ f32        ┆           │
╞═════════════╪══════════╪══════════╪═══════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ Karl-Anthon ┆ Towns    ┆ 1626157  ┆ 24.767124 ┆ … ┆ 0.02243  ┆ 0.0      ┆ 3.038804   ┆ 0.856735  │
│ y           ┆          ┆          ┆           ┆   ┆          ┆          ┆            ┆           │
│ Mikal       ┆ Bridges  ┆ 1628969  ┆ 14.453997 ┆ … ┆ 2.606043 ┆ 0.728308 ┆ 10.440793  ┆ 9.481155  │
│ OG          ┆ Anunoby  ┆ 1628384  ┆ 27.45118  ┆ … ┆ 0.00204  ┆ 2.314866 ┆ 10.908648  ┆ 1.49482   │
│ Jalen       ┆ Brunson  ┆ 1628973  ┆ 24.209377 ┆ … ┆ 1.022304 ┆ 0.003147 ┆ 8.669761   ┆ 1.406437  │
│ Miles       ┆ McBride  ┆ 1630540  ┆ 8.667492  ┆ … ┆ 0.001319 ┆ 0.577933 ┆ 14.273738  ┆ 1.795496  │
│ …           ┆ …        ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ Ariel       ┆ Hukporti ┆ 1630574  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.013652 ┆ 0.003178   ┆ 0.0       │
│ Tyler       ┆ Kolek    ┆ 1642278  ┆ 0.000803  ┆ … ┆ 0.0      ┆ 0.001046 ┆ 0.0        ┆ 0.0       │
│ Jacob       ┆ Toppin   ┆ 1631210  ┆ 0.003803  ┆ … ┆ 0.003229 ┆ 0.0      ┆ 0.00247    ┆ 0.008193  │
│ null        ┆ null     ┆ null     ┆ 0.010089  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0       │
│ null        ┆ null     ┆ null     ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.001736 ┆ 0.0        ┆ 0.004337  │
└─────────────┴──────────┴──────────┴───────────┴───┴──────────┴──────────┴────────────┴───────────┘