In [83]:
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
from gamePredModel import GamePredModel, mdn_loss, players_and_stats
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split

In [138]:
INPUT_DIM = 1350
HIDDEN_DIM = 4096
OUTPUT_DIM = 150
N_COMPONENTS = 2
BATCH_SIZE = 64
GAME_ID = 22400367

In [139]:
data = pd.read_csv("../csv/data.csv")
all_cols = data.columns.tolist()
cols_to_drop = []
stats_to_drop =[
    'fieldgoalsattempted',
    'fieldgoalsmade',
    'fieldgoalspercentage',
    'threepointersattempted',
    'threepointersmade',
    'threepointerspercentage',
    'freethrowsattempted',
    'freethrowsmade',
    'freethrowspercentage',
    'reboundsdefensive',
    'reboundsoffensive',
    'reboundstotal',
    'foulspersonal',
]
for tn in ['t0', 't1']:
    for pidx in range(15):
        for stat in stats_to_drop:
            cols_to_drop.append(f'{tn}_p{pidx}_{stat}')

print(len(cols_to_drop), cols_to_drop)
data = data.drop(columns=cols_to_drop)

390 ['t0_p0_fieldgoalsattempted', 't0_p0_fieldgoalsmade', 't0_p0_fieldgoalspercentage', 't0_p0_threepointersattempted', 't0_p0_threepointersmade', 't0_p0_threepointerspercentage', 't0_p0_freethrowsattempted', 't0_p0_freethrowsmade', 't0_p0_freethrowspercentage', 't0_p0_reboundsdefensive', 't0_p0_reboundsoffensive', 't0_p0_reboundstotal', 't0_p0_foulspersonal', 't0_p1_fieldgoalsattempted', 't0_p1_fieldgoalsmade', 't0_p1_fieldgoalspercentage', 't0_p1_threepointersattempted', 't0_p1_threepointersmade', 't0_p1_threepointerspercentage', 't0_p1_freethrowsattempted', 't0_p1_freethrowsmade', 't0_p1_freethrowspercentage', 't0_p1_reboundsdefensive', 't0_p1_reboundsoffensive', 't0_p1_reboundstotal', 't0_p1_foulspersonal', 't0_p2_fieldgoalsattempted', 't0_p2_fieldgoalsmade', 't0_p2_fieldgoalspercentage', 't0_p2_threepointersattempted', 't0_p2_threepointersmade', 't0_p2_threepointerspercentage', 't0_p2_freethrowsattempted', 't0_p2_freethrowsmade', 't0_p2_freethrowspercentage', 't0_p2_reboundsdefensive', 't0_p2_reboundsoffensive', 't0_p2_reboundstotal', 't0_p2_foulspersonal', 't0_p3_fieldgoalsattempted', 't0_p3_fieldgoalsmade', 't0_p3_fieldgoalspercentage', 't0_p3_threepointersattempted', 't0_p3_threepointersmade', 't0_p3_threepointerspercentage', 't0_p3_freethrowsattempted', 't0_p3_freethrowsmade', 't0_p3_freethrowspercentage', 't0_p3_reboundsdefensive', 't0_p3_reboundsoffensive', 't0_p3_reboundstotal', 't0_p3_foulspersonal', 't0_p4_fieldgoalsattempted', 't0_p4_fieldgoalsmade', 't0_p4_fieldgoalspercentage', 't0_p4_threepointersattempted', 't0_p4_threepointersmade', 't0_p4_threepointerspercentage', 't0_p4_freethrowsattempted', 't0_p4_freethrowsmade', 't0_p4_freethrowspercentage', 't0_p4_reboundsdefensive', 't0_p4_reboundsoffensive', 't0_p4_reboundstotal', 't0_p4_foulspersonal', 't0_p5_fieldgoalsattempted', 't0_p5_fieldgoalsmade', 't0_p5_fieldgoalspercentage', 't0_p5_threepointersattempted', 't0_p5_threepointersmade', 't0_p5_threepointerspercentage', 't0_p5_freethrowsattempted', 't0_p5_freethrowsmade', 't0_p5_freethrowspercentage', 't0_p5_reboundsdefensive', 't0_p5_reboundsoffensive', 't0_p5_reboundstotal', 't0_p5_foulspersonal', 't0_p6_fieldgoalsattempted', 't0_p6_fieldgoalsmade', 't0_p6_fieldgoalspercentage', 't0_p6_threepointersattempted', 't0_p6_threepointersmade', 't0_p6_threepointerspercentage', 't0_p6_freethrowsattempted', 't0_p6_freethrowsmade', 't0_p6_freethrowspercentage', 't0_p6_reboundsdefensive', 't0_p6_reboundsoffensive', 't0_p6_reboundstotal', 't0_p6_foulspersonal', 't0_p7_fieldgoalsattempted', 't0_p7_fieldgoalsmade', 't0_p7_fieldgoalspercentage', 't0_p7_threepointersattempted', 't0_p7_threepointersmade', 't0_p7_threepointerspercentage', 't0_p7_freethrowsattempted', 't0_p7_freethrowsmade', 't0_p7_freethrowspercentage', 't0_p7_reboundsdefensive', 't0_p7_reboundsoffensive', 't0_p7_reboundstotal', 't0_p7_foulspersonal', 't0_p8_fieldgoalsattempted', 't0_p8_fieldgoalsmade', 't0_p8_fieldgoalspercentage', 't0_p8_threepointersattempted', 't0_p8_threepointersmade', 't0_p8_threepointerspercentage', 't0_p8_freethrowsattempted', 't0_p8_freethrowsmade', 't0_p8_freethrowspercentage', 't0_p8_reboundsdefensive', 't0_p8_reboundsoffensive', 't0_p8_reboundstotal', 't0_p8_foulspersonal', 't0_p9_fieldgoalsattempted', 't0_p9_fieldgoalsmade', 't0_p9_fieldgoalspercentage', 't0_p9_threepointersattempted', 't0_p9_threepointersmade', 't0_p9_threepointerspercentage', 't0_p9_freethrowsattempted', 't0_p9_freethrowsmade', 't0_p9_freethrowspercentage', 't0_p9_reboundsdefensive', 't0_p9_reboundsoffensive', 't0_p9_reboundstotal', 't0_p9_foulspersonal', 't0_p10_fieldgoalsattempted', 't0_p10_fieldgoalsmade', 't0_p10_fieldgoalspercentage', 't0_p10_threepointersattempted', 't0_p10_threepointersmade', 't0_p10_threepointerspercentage', 't0_p10_freethrowsattempted', 't0_p10_freethrowsmade', 't0_p10_freethrowspercentage', 't0_p10_reboundsdefensive', 't0_p10_reboundsoffensive', 't0_p10_reboundstotal', 't0_p10_foulspersonal', 't0_p11_fieldgoalsattempted', 't0_p11_fieldgoalsmade', 't0_p11_fieldgoalspercentage', 't0_p11_threepointersattempted', 't0_p11_threepointersmade', 't0_p11_threepointerspercentage', 't0_p11_freethrowsattempted', 't0_p11_freethrowsmade', 't0_p11_freethrowspercentage', 't0_p11_reboundsdefensive', 't0_p11_reboundsoffensive', 't0_p11_reboundstotal', 't0_p11_foulspersonal', 't0_p12_fieldgoalsattempted', 't0_p12_fieldgoalsmade', 't0_p12_fieldgoalspercentage', 't0_p12_threepointersattempted', 't0_p12_threepointersmade', 't0_p12_threepointerspercentage', 't0_p12_freethrowsattempted', 't0_p12_freethrowsmade', 't0_p12_freethrowspercentage', 't0_p12_reboundsdefensive', 't0_p12_reboundsoffensive', 't0_p12_reboundstotal', 't0_p12_foulspersonal', 't0_p13_fieldgoalsattempted', 't0_p13_fieldgoalsmade', 't0_p13_fieldgoalspercentage', 't0_p13_threepointersattempted', 't0_p13_threepointersmade', 't0_p13_threepointerspercentage', 't0_p13_freethrowsattempted', 't0_p13_freethrowsmade', 't0_p13_freethrowspercentage', 't0_p13_reboundsdefensive', 't0_p13_reboundsoffensive', 't0_p13_reboundstotal', 't0_p13_foulspersonal', 't0_p14_fieldgoalsattempted', 't0_p14_fieldgoalsmade', 't0_p14_fieldgoalspercentage', 't0_p14_threepointersattempted', 't0_p14_threepointersmade', 't0_p14_threepointerspercentage', 't0_p14_freethrowsattempted', 't0_p14_freethrowsmade', 't0_p14_freethrowspercentage', 't0_p14_reboundsdefensive', 't0_p14_reboundsoffensive', 't0_p14_reboundstotal', 't0_p14_foulspersonal', 't1_p0_fieldgoalsattempted', 't1_p0_fieldgoalsmade', 't1_p0_fieldgoalspercentage', 't1_p0_threepointersattempted', 't1_p0_threepointersmade', 't1_p0_threepointerspercentage', 't1_p0_freethrowsattempted', 't1_p0_freethrowsmade', 't1_p0_freethrowspercentage', 't1_p0_reboundsdefensive', 't1_p0_reboundsoffensive', 't1_p0_reboundstotal', 't1_p0_foulspersonal', 't1_p1_fieldgoalsattempted', 't1_p1_fieldgoalsmade', 't1_p1_fieldgoalspercentage', 't1_p1_threepointersattempted', 't1_p1_threepointersmade', 't1_p1_threepointerspercentage', 't1_p1_freethrowsattempted', 't1_p1_freethrowsmade', 't1_p1_freethrowspercentage', 't1_p1_reboundsdefensive', 't1_p1_reboundsoffensive', 't1_p1_reboundstotal', 't1_p1_foulspersonal', 't1_p2_fieldgoalsattempted', 't1_p2_fieldgoalsmade', 't1_p2_fieldgoalspercentage', 't1_p2_threepointersattempted', 't1_p2_threepointersmade', 't1_p2_threepointerspercentage', 't1_p2_freethrowsattempted', 't1_p2_freethrowsmade', 't1_p2_freethrowspercentage', 't1_p2_reboundsdefensive', 't1_p2_reboundsoffensive', 't1_p2_reboundstotal', 't1_p2_foulspersonal', 't1_p3_fieldgoalsattempted', 't1_p3_fieldgoalsmade', 't1_p3_fieldgoalspercentage', 't1_p3_threepointersattempted', 't1_p3_threepointersmade', 't1_p3_threepointerspercentage', 't1_p3_freethrowsattempted', 't1_p3_freethrowsmade', 't1_p3_freethrowspercentage', 't1_p3_reboundsdefensive', 't1_p3_reboundsoffensive', 't1_p3_reboundstotal', 't1_p3_foulspersonal', 't1_p4_fieldgoalsattempted', 't1_p4_fieldgoalsmade', 't1_p4_fieldgoalspercentage', 't1_p4_threepointersattempted', 't1_p4_threepointersmade', 't1_p4_threepointerspercentage', 't1_p4_freethrowsattempted', 't1_p4_freethrowsmade', 't1_p4_freethrowspercentage', 't1_p4_reboundsdefensive', 't1_p4_reboundsoffensive', 't1_p4_reboundstotal', 't1_p4_foulspersonal', 't1_p5_fieldgoalsattempted', 't1_p5_fieldgoalsmade', 't1_p5_fieldgoalspercentage', 't1_p5_threepointersattempted', 't1_p5_threepointersmade', 't1_p5_threepointerspercentage', 't1_p5_freethrowsattempted', 't1_p5_freethrowsmade', 't1_p5_freethrowspercentage', 't1_p5_reboundsdefensive', 't1_p5_reboundsoffensive', 't1_p5_reboundstotal', 't1_p5_foulspersonal', 't1_p6_fieldgoalsattempted', 't1_p6_fieldgoalsmade', 't1_p6_fieldgoalspercentage', 't1_p6_threepointersattempted', 't1_p6_threepointersmade', 't1_p6_threepointerspercentage', 't1_p6_freethrowsattempted', 't1_p6_freethrowsmade', 't1_p6_freethrowspercentage', 't1_p6_reboundsdefensive', 't1_p6_reboundsoffensive', 't1_p6_reboundstotal', 't1_p6_foulspersonal', 't1_p7_fieldgoalsattempted', 't1_p7_fieldgoalsmade', 't1_p7_fieldgoalspercentage', 't1_p7_threepointersattempted', 't1_p7_threepointersmade', 't1_p7_threepointerspercentage', 't1_p7_freethrowsattempted', 't1_p7_freethrowsmade', 't1_p7_freethrowspercentage', 't1_p7_reboundsdefensive', 't1_p7_reboundsoffensive', 't1_p7_reboundstotal', 't1_p7_foulspersonal', 't1_p8_fieldgoalsattempted', 't1_p8_fieldgoalsmade', 't1_p8_fieldgoalspercentage', 't1_p8_threepointersattempted', 't1_p8_threepointersmade', 't1_p8_threepointerspercentage', 't1_p8_freethrowsattempted', 't1_p8_freethrowsmade', 't1_p8_freethrowspercentage', 't1_p8_reboundsdefensive', 't1_p8_reboundsoffensive', 't1_p8_reboundstotal', 't1_p8_foulspersonal', 't1_p9_fieldgoalsattempted', 't1_p9_fieldgoalsmade', 't1_p9_fieldgoalspercentage', 't1_p9_threepointersattempted', 't1_p9_threepointersmade', 't1_p9_threepointerspercentage', 't1_p9_freethrowsattempted', 't1_p9_freethrowsmade', 't1_p9_freethrowspercentage', 't1_p9_reboundsdefensive', 't1_p9_reboundsoffensive', 't1_p9_reboundstotal', 't1_p9_foulspersonal', 't1_p10_fieldgoalsattempted', 't1_p10_fieldgoalsmade', 't1_p10_fieldgoalspercentage', 't1_p10_threepointersattempted', 't1_p10_threepointersmade', 't1_p10_threepointerspercentage', 't1_p10_freethrowsattempted', 't1_p10_freethrowsmade', 't1_p10_freethrowspercentage', 't1_p10_reboundsdefensive', 't1_p10_reboundsoffensive', 't1_p10_reboundstotal', 't1_p10_foulspersonal', 't1_p11_fieldgoalsattempted', 't1_p11_fieldgoalsmade', 't1_p11_fieldgoalspercentage', 't1_p11_threepointersattempted', 't1_p11_threepointersmade', 't1_p11_threepointerspercentage', 't1_p11_freethrowsattempted', 't1_p11_freethrowsmade', 't1_p11_freethrowspercentage', 't1_p11_reboundsdefensive', 't1_p11_reboundsoffensive', 't1_p11_reboundstotal', 't1_p11_foulspersonal', 't1_p12_fieldgoalsattempted', 't1_p12_fieldgoalsmade', 't1_p12_fieldgoalspercentage', 't1_p12_threepointersattempted', 't1_p12_threepointersmade', 't1_p12_threepointerspercentage', 't1_p12_freethrowsattempted', 't1_p12_freethrowsmade', 't1_p12_freethrowspercentage', 't1_p12_reboundsdefensive', 't1_p12_reboundsoffensive', 't1_p12_reboundstotal', 't1_p12_foulspersonal', 't1_p13_fieldgoalsattempted', 't1_p13_fieldgoalsmade', 't1_p13_fieldgoalspercentage', 't1_p13_threepointersattempted', 't1_p13_threepointersmade', 't1_p13_threepointerspercentage', 't1_p13_freethrowsattempted', 't1_p13_freethrowsmade', 't1_p13_freethrowspercentage', 't1_p13_reboundsdefensive', 't1_p13_reboundsoffensive', 't1_p13_reboundstotal', 't1_p13_foulspersonal', 't1_p14_fieldgoalsattempted', 't1_p14_fieldgoalsmade', 't1_p14_fieldgoalspercentage', 't1_p14_threepointersattempted', 't1_p14_threepointersmade', 't1_p14_threepointerspercentage', 't1_p14_freethrowsattempted', 't1_p14_freethrowsmade', 't1_p14_freethrowspercentage', 't1_p14_reboundsdefensive', 't1_p14_reboundsoffensive', 't1_p14_reboundstotal', 't1_p14_foulspersonal']

In [140]:
print(data.shape)

(57340, 1534)

In [141]:
train_data = data.iloc[:, 34:]

In [142]:
train_data.head()

,t0_p0_points,t0_p1_points,t0_p2_points,t0_p3_points,t0_p4_points,t0_p5_points,t0_p6_points,t0_p7_points,t0_p8_points,t0_p9_points,...,t1_p5_numminutes,t1_p6_numminutes,t1_p7_numminutes,t1_p8_numminutes,t1_p9_numminutes,t1_p10_numminutes,t1_p11_numminutes,t1_p12_numminutes,t1_p13_numminutes,t1_p14_numminutes
0,21.0,11.0,7.0,8.0,7.0,0.0,0.0,0.0,0.0,0.0,...,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,33.0,28.0,18.0,6.0,0.0,6.0,16.0,5.0,0.0,0.0,...,18.0,16.0,12.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6.0,18.0,20.0,8.0,12.0,0.0,0.0,0.0,0.0,0.0,...,21.0,20.0,10.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
3,35.0,17.0,24.0,14.0,12.0,6.0,0.0,0.0,0.0,0.0,...,16.0,11.0,9.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,14.0,15.0,19.0,4.0,10.0,11.0,6.0,0.0,0.0,0.0,...,14.0,12.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [143]:
# # Move first 30 columns to the end of the DataFrame
# first_30 = train_data.columns[:30].tolist()
# rest = train_data.columns[30:].tolist()
# train_data = train_data[rest + first_30]
# train_data

In [144]:
model = GamePredModel(input_dim=INPUT_DIM, hidden_dim=HIDDEN_DIM, output_dim=OUTPUT_DIM, n_components=N_COMPONENTS)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = mdn_loss
num_epochs = 3

In [145]:




model = GamePredModel(input_dim=INPUT_DIM, hidden_dim=HIDDEN_DIM, output_dim=OUTPUT_DIM, n_components=N_COMPONENTS)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = mdn_loss
num_epochs = 3

# Step 2: Split features and target
X = train_data.iloc[:, OUTPUT_DIM:]
y = train_data.iloc[:, :OUTPUT_DIM]

print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# # Step 4: To tensors
X_train_tensor = torch.tensor(X_train.values, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32)

X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

# Step 5: DataLoader
train_loader = DataLoader(
    TensorDataset(X_train_tensor, y_train_tensor), batch_size=BATCH_SIZE, shuffle=True
)
test_loader = DataLoader(TensorDataset(X_test_tensor, y_test_tensor), batch_size=BATCH_SIZE)
print(train_data.shape)
train_data.describe()

for epoch in range(num_epochs):
    model.train()
    total_loss = 0.0
    epoch_start = time.time()

    for i, (batch_x, batch_y) in enumerate(train_loader, 1):
        batch_start = time.time()
        optimizer.zero_grad()

        # Forward pass
        pi, mu, sigma = model(batch_x)

        # Loss computation
        loss = mdn_loss(pi, mu, sigma, batch_y)
        total_loss += loss.item()

        # Backpropagation
        loss.backward()
        optimizer.step()

        batch_time = time.time() - batch_start
        if i % 100 == 0 or i == len(train_loader):
            print(
                f"Batch {i:3d}/{len(train_loader)} - Loss: {loss.item():.6f} - Time: {batch_time:.2f}s"
            )

    avg_train_loss = total_loss / len(train_loader)
    epoch_time = time.time() - epoch_start

    # ----- Evaluation -----
    model.eval()
    total_test_loss = 0.0
    with torch.no_grad():
        for batch_x, batch_y in test_loader:
            pi, mu, sigma = model(batch_x)
            test_loss = mdn_loss(pi, mu, sigma, batch_y)
            total_test_loss += test_loss.item()

    avg_test_loss = total_test_loss / len(test_loader)

    # ----- Logging -----
    print(f"\nEpoch [{epoch+1}/{num_epochs}] Summary:")
    print(f"  Train Loss : {avg_train_loss:.6f}")
    print(f"  Test Loss  : {avg_test_loss:.6f}")
    print(f"  Epoch Time : {epoch_time:.2f}s")
    print("-" * 60)

(57340, 1350)
(57340, 150)
(57340, 1500)
Batch 100/717 - Loss: 0.435147 - Time: 0.11s
Batch 200/717 - Loss: -0.095909 - Time: 0.11s
Batch 300/717 - Loss: 0.628951 - Time: 0.11s
Batch 400/717 - Loss: -0.250545 - Time: 0.11s
Batch 500/717 - Loss: -0.563578 - Time: 0.10s
Batch 600/717 - Loss: -0.281698 - Time: 0.11s
Batch 700/717 - Loss: 0.051593 - Time: 0.11s
Batch 717/717 - Loss: -0.105158 - Time: 0.10s

Epoch [1/3] Summary:
  Train Loss : 0.022023
  Test Loss  : -0.392616
  Epoch Time : 74.94s
------------------------------------------------------------
Batch 100/717 - Loss: -0.528553 - Time: 0.11s
Batch 200/717 - Loss: -0.397522 - Time: 0.11s
Batch 300/717 - Loss: -0.736391 - Time: 0.11s
Batch 400/717 - Loss: -0.269610 - Time: 0.11s
Batch 500/717 - Loss: -0.918027 - Time: 0.11s
Batch 600/717 - Loss: -0.511253 - Time: 0.11s
Batch 700/717 - Loss: -0.742390 - Time: 0.10s
Batch 717/717 - Loss: -0.852830 - Time: 0.10s

Epoch [2/3] Summary:
  Train Loss : -0.468447
  Test Loss  : -0.842045
  Epoch Time : 77.36s
------------------------------------------------------------
Batch 100/717 - Loss: -0.915009 - Time: 0.12s
Batch 200/717 - Loss: -0.874030 - Time: 0.11s
Batch 300/717 - Loss: -0.720536 - Time: 0.11s
Batch 400/717 - Loss: -0.405458 - Time: 0.11s
Batch 500/717 - Loss: -1.228766 - Time: 0.11s
Batch 600/717 - Loss: -1.262695 - Time: 0.11s
Batch 700/717 - Loss: -1.381473 - Time: 0.11s
Batch 717/717 - Loss: -1.414801 - Time: 0.09s

Epoch [3/3] Summary:
  Train Loss : -0.829618
  Test Loss  : -1.258045
  Epoch Time : 76.92s
------------------------------------------------------------

In [146]:
# # After training
torch.save(model.state_dict(), "game_pred_mdn.pt")

In [147]:
torch.save({
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
}, "game_pred_mdn_full.pt")

In [148]:
model = GamePredModel(input_dim=INPUT_DIM, hidden_dim=HIDDEN_DIM, output_dim=OUTPUT_DIM, n_components=N_COMPONENTS)
model.load_state_dict(torch.load("game_pred_mdn.pt"))
model.eval()  # set to evaluation mode

checkpoint = torch.load("game_pred_mdn_full.pt")
model.load_state_dict(checkpoint["model_state_dict"])
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
optimizer.load_state_dict(checkpoint["optimizer_state_dict"])

In [149]:
game_data = data[data["game_id"] == GAME_ID].iloc[0, 34:]
X_input = game_data.iloc[OUTPUT_DIM:]
game_data

t0_p0_points          9.0
t0_p1_points         14.0
t0_p2_points         16.0
t0_p3_points         13.0
t0_p4_points          6.0
                     ...
t1_p10_numminutes     0.0
t1_p11_numminutes     0.0
t1_p12_numminutes     0.0
t1_p13_numminutes     0.0
t1_p14_numminutes     0.0
Name: 12823, Length: 1500, dtype: object

In [150]:
X_input = X_input.astype(float)
X_input.describe()

count    1350.000000
mean        1.673128
std         8.347921
min         0.000000
25%         0.000000
50%         0.000000
75%         0.533250
max       248.000000
Name: 12823, dtype: float64

In [151]:
X_tensor = torch.tensor(X_input.values, dtype=torch.float32)
X_tensor = X_tensor.view(1, -1)
print(X_tensor)
model.eval()  # if not already in eval mode
with torch.no_grad():
    pi, mu, sigma = model(X_tensor)

tensor([[13.0000, 23.4000, 13.1000,  ...,  0.0000,  0.0000,  0.0000]])

In [152]:
pi

tensor([[[9.9982e-01, 1.8256e-04],
         [4.9256e-03, 9.9507e-01],
         [9.9804e-01, 1.9581e-03],
         [8.8381e-01, 1.1619e-01],
         [7.6474e-01, 2.3526e-01],
         [3.9204e-01, 6.0796e-01],
         [5.6108e-01, 4.3892e-01],
         [2.9167e-01, 7.0833e-01],
         [1.4711e-01, 8.5289e-01],
         [6.2462e-02, 9.3754e-01],
         [9.7663e-01, 2.3372e-02],
         [2.4572e-02, 9.7543e-01],
         [9.9113e-01, 8.8711e-03],
         [4.0842e-02, 9.5916e-01],
         [7.1131e-03, 9.9289e-01],
         [3.4864e-04, 9.9965e-01],
         [9.9446e-01, 5.5415e-03],
         [9.8066e-01, 1.9343e-02],
         [9.9155e-02, 9.0084e-01],
         [4.3151e-03, 9.9568e-01],
         [3.7540e-01, 6.2460e-01],
         [4.3841e-01, 5.6159e-01],
         [3.0286e-01, 6.9714e-01],
         [1.6553e-01, 8.3447e-01],
         [8.9690e-02, 9.1031e-01],
         [9.7960e-01, 2.0402e-02],
         [9.8453e-01, 1.5465e-02],
         [9.9107e-01, 8.9303e-03],
         [9.9343e-01, 6.5714e-03],
         [9.3763e-03, 9.9062e-01],
         [3.6390e-01, 6.3610e-01],
         [3.4386e-01, 6.5614e-01],
         [6.9353e-01, 3.0647e-01],
         [9.9718e-01, 2.8177e-03],
         [6.6204e-01, 3.3796e-01],
         [5.2981e-01, 4.7019e-01],
         [3.0620e-01, 6.9380e-01],
         [1.9937e-01, 8.0063e-01],
         [9.7322e-01, 2.6783e-02],
         [6.3404e-02, 9.3660e-01],
         [1.8296e-02, 9.8170e-01],
         [9.9063e-01, 9.3701e-03],
         [1.0733e-02, 9.8927e-01],
         [9.9680e-01, 3.2019e-03],
         [1.0036e-02, 9.8996e-01],
         [6.5193e-01, 3.4807e-01],
         [6.2644e-01, 3.7356e-01],
         [3.1910e-01, 6.8090e-01],
         [6.7822e-01, 3.2178e-01],
         [3.8518e-01, 6.1482e-01],
         [5.5582e-01, 4.4418e-01],
         [3.4788e-01, 6.5212e-01],
         [1.1687e-02, 9.8831e-01],
         [1.0488e-01, 8.9512e-01],
         [9.6231e-01, 3.7687e-02],
         [2.8423e-02, 9.7158e-01],
         [5.9005e-03, 9.9410e-01],
         [9.7525e-01, 2.4752e-02],
         [2.3276e-02, 9.7672e-01],
         [9.8737e-01, 1.2627e-02],
         [9.9542e-01, 4.5774e-03],
         [6.0221e-01, 3.9779e-01],
         [6.2587e-01, 3.7413e-01],
         [6.6816e-01, 3.3184e-01],
         [7.1010e-01, 2.8990e-01],
         [8.0499e-01, 1.9501e-01],
         [8.3563e-01, 1.6437e-01],
         [8.7568e-02, 9.1243e-01],
         [4.9163e-02, 9.5084e-01],
         [9.8245e-01, 1.7548e-02],
         [9.9627e-01, 3.7282e-03],
         [1.0046e-02, 9.8995e-01],
         [3.9938e-03, 9.9601e-01],
         [3.4697e-03, 9.9653e-01],
         [3.6847e-03, 9.9632e-01],
         [4.5300e-01, 5.4700e-01],
         [5.5329e-01, 4.4671e-01],
         [6.1629e-01, 3.8371e-01],
         [2.7438e-01, 7.2562e-01],
         [3.1176e-01, 6.8824e-01],
         [7.6814e-01, 2.3186e-01],
         [8.4031e-01, 1.5969e-01],
         [1.3487e-01, 8.6513e-01],
         [4.9063e-02, 9.5094e-01],
         [1.8464e-02, 9.8154e-01],
         [9.9320e-01, 6.7964e-03],
         [9.8982e-01, 1.0175e-02],
         [9.9130e-01, 8.6998e-03],
         [3.2259e-03, 9.9677e-01],
         [9.8826e-01, 1.1743e-02],
         [5.4403e-01, 4.5597e-01],
         [5.9144e-01, 4.0856e-01],
         [6.5507e-01, 3.4493e-01],
         [5.1692e-01, 4.8308e-01],
         [3.5869e-01, 6.4131e-01],
         [7.0074e-01, 2.9926e-01],
         [2.2425e-01, 7.7575e-01],
         [9.9202e-01, 7.9781e-03],
         [9.4411e-01, 5.5886e-02],
         [9.7695e-01, 2.3052e-02],
         [9.8930e-01, 1.0703e-02],
         [1.8041e-02, 9.8196e-01],
         [9.7194e-01, 2.8065e-02],
         [1.2990e-02, 9.8701e-01],
         [9.9231e-01, 7.6890e-03],
         [5.5901e-01, 4.4099e-01],
         [5.9477e-01, 4.0523e-01],
         [3.4910e-01, 6.5090e-01],
         [3.8743e-02, 9.6126e-01],
         [6.0734e-01, 3.9266e-01],
         [6.8097e-01, 3.1903e-01],
         [2.0341e-01, 7.9659e-01],
         [8.7764e-01, 1.2236e-01],
         [5.9514e-02, 9.4049e-01],
         [2.6152e-02, 9.7385e-01],
         [9.8628e-01, 1.3719e-02],
         [2.8579e-02, 9.7142e-01],
         [1.0853e-02, 9.8915e-01],
         [9.9785e-01, 2.1529e-03],
         [9.8021e-01, 1.9790e-02],
         [6.7365e-01, 3.2635e-01],
         [6.9555e-01, 3.0445e-01],
         [3.4250e-01, 6.5750e-01],
         [5.4651e-01, 4.5349e-01],
         [5.4098e-01, 4.5902e-01],
         [4.1290e-01, 5.8710e-01],
         [3.1788e-01, 6.8212e-01],
         [7.8264e-01, 2.1736e-01],
         [1.9352e-02, 9.8065e-01],
         [9.5800e-01, 4.1996e-02],
         [1.4891e-02, 9.8511e-01],
         [8.0461e-03, 9.9195e-01],
         [1.7421e-02, 9.8258e-01],
         [8.8627e-03, 9.9114e-01],
         [1.1811e-02, 9.8819e-01],
         [3.0031e-01, 6.9969e-01],
         [3.1046e-01, 6.8954e-01],
         [6.3453e-01, 3.6547e-01],
         [4.5298e-01, 5.4702e-01],
         [1.3477e-02, 9.8652e-01],
         [8.5630e-03, 9.9144e-01],
         [3.1210e-01, 6.8790e-01],
         [8.0690e-01, 1.9310e-01],
         [1.1290e-01, 8.8710e-01],
         [7.8925e-02, 9.2108e-01],
         [9.8537e-01, 1.4625e-02],
         [9.9554e-01, 4.4598e-03],
         [1.3413e-02, 9.8659e-01],
         [9.9085e-01, 9.1460e-03],
         [9.8918e-01, 1.0825e-02]]])

In [153]:
mu

tensor([[[ 1.8514e+01,  9.0212e-01],
         [ 3.4030e-02,  1.5458e+01],
         [ 1.2428e+01,  2.3700e-01],
         [ 1.0009e+01,  4.5194e-03],
         [ 8.2551e+00,  4.9719e-03],
         [-3.8694e-03,  6.7923e+00],
         [-5.3356e-04,  5.4914e+00],
         [ 4.2802e+00,  5.3442e-03],
         [ 3.7390e+00,  2.8282e-03],
         [ 2.8783e+00,  2.5162e-03],
         [-3.0817e-03,  1.3257e+00],
         [ 2.4359e-01, -1.4430e-03],
         [ 1.2015e-04,  8.5531e-02],
         [-2.0929e-01, -5.3066e-04],
         [ 1.4253e-02,  8.2225e-04],
         [ 6.2021e-01,  1.8632e+01],
         [ 1.5725e+01,  2.6867e-03],
         [ 1.3058e+01, -1.3674e-01],
         [ 1.9254e-02,  1.0544e+01],
         [-1.1180e-01,  7.3752e+00],
         [ 1.8833e-03,  7.0029e+00],
         [ 5.7287e+00, -7.6556e-04],
         [ 4.6667e+00, -2.8829e-03],
         [ 3.8518e+00, -6.8372e-03],
         [ 7.2061e-01,  1.9939e-03],
         [ 2.2899e-03,  1.7835e+00],
         [ 4.8336e-03,  2.1511e-01],
         [-1.7514e-03,  1.1971e-01],
         [ 9.2061e-04,  6.3396e-02],
         [ 3.9273e-03,  4.9259e-03],
         [ 6.3814e+00,  2.3893e+00],
         [ 5.7031e+00,  1.7807e+00],
         [ 1.4509e+00,  4.9503e+00],
         [ 1.9021e+00,  1.5730e-01],
         [ 2.7360e-01,  2.5192e+00],
         [ 1.8526e-03,  1.8748e+00],
         [ 1.6524e+00,  2.8635e-03],
         [ 1.4424e+00, -4.0512e-04],
         [ 1.0298e-01,  1.2461e-01],
         [ 4.1985e-01, -2.6888e-04],
         [ 2.9928e-01, -2.0617e-03],
         [ 1.8557e-03,  1.9397e-01],
         [-3.9611e-02, -7.9460e-03],
         [ 2.2651e-03,  1.7476e-01],
         [-1.2993e-02,  4.3329e-04],
         [ 2.5222e+00,  6.6706e+00],
         [ 2.0233e+00,  6.1809e+00],
         [ 5.1046e+00,  1.5487e+00],
         [ 9.9152e-01,  3.8977e+00],
         [-6.9666e-03,  2.2953e+00],
         [ 5.7372e-03,  1.9770e+00],
         [ 1.7758e+00,  8.8355e-04],
         [ 8.5242e-02,  2.5093e-01],
         [ 1.2091e+00, -3.3666e-03],
         [-1.6289e-03,  9.2608e-01],
         [ 3.0169e-01,  1.1983e-03],
         [-2.2290e-02,  4.8738e-04],
         [-5.0109e-03,  2.1081e-03],
         [-3.9874e-03, -1.4549e-03],
         [ 1.9226e-03,  3.3152e-03],
         [ 6.2365e-01,  9.3239e-02],
         [ 3.5308e-03,  1.5055e+00],
         [-2.8569e-03,  1.5185e+00],
         [-5.5763e-03,  1.3787e+00],
         [-1.3517e-03,  1.2750e+00],
         [-7.9465e-04,  1.3095e+00],
         [-2.3451e-03,  7.2343e-01],
         [ 1.0171e+00,  2.2182e-03],
         [ 6.9872e-01,  1.2017e-03],
         [-9.4833e-04,  7.0006e-01],
         [ 2.2888e-03,  2.0211e-01],
         [-8.1574e-03,  1.6225e-03],
         [ 2.7134e-01, -2.7223e-04],
         [-3.9501e-01,  5.5613e-03],
         [-3.2855e-01, -4.6043e-03],
         [ 1.7037e+00, -7.7024e-03],
         [-5.9327e-03,  1.4688e+00],
         [ 6.1755e-04,  1.6211e+00],
         [ 1.3716e+00,  1.4862e-03],
         [ 1.3857e+00,  9.2600e-05],
         [ 1.5315e-04,  1.2642e+00],
         [ 4.7740e-04,  1.1871e+00],
         [ 4.6468e-01, -4.9736e-03],
         [ 9.3430e-01,  7.2204e-03],
         [ 5.9182e-01,  1.6831e-03],
         [ 7.1100e-03,  1.4771e-01],
         [-5.6854e-05,  1.4474e-02],
         [-2.4300e-03, -2.4677e-02],
         [ 2.1928e-01, -6.2535e-05],
         [ 2.0430e-03,  3.4151e-02],
         [ 4.6883e-01,  1.9917e+00],
         [ 4.2880e-01,  1.8397e+00],
         [ 2.9383e-01,  1.8256e+00],
         [-5.1769e-03,  1.3137e+00],
         [ 1.2372e+00,  8.7311e-04],
         [-2.1715e-03,  1.1933e+00],
         [ 9.8020e-01, -3.3843e-03],
         [ 8.7571e-02,  9.3596e-02],
         [ 2.0338e-03,  9.7572e-01],
         [-4.6523e-03,  8.0467e-01],
         [ 4.2993e-03,  8.4280e-02],
         [-4.1856e-02,  5.6943e-03],
         [ 7.7818e-03,  5.7695e-03],
         [ 4.7692e-04, -8.3148e-03],
         [ 3.8688e-03,  5.4358e-01],
         [ 5.4807e-01,  2.0712e+00],
         [ 4.5683e-01,  1.9073e+00],
         [ 1.8056e+00,  4.3419e-01],
         [-1.0294e-01,  7.1719e-01],
         [-1.5251e-03,  1.2965e+00],
         [ 4.1251e-03,  1.1674e+00],
         [ 1.1465e+00,  2.6098e-03],
         [-5.7730e-03,  1.0749e+00],
         [ 6.8084e-01,  4.8605e-03],
         [ 6.5736e-01, -3.0102e-03],
         [-5.3435e-04,  1.9333e-01],
         [ 4.4517e-03, -4.1619e-04],
         [-5.2019e-02,  8.4899e-05],
         [ 5.9061e-04, -6.7968e-01],
         [-9.9503e-03,  1.0495e-02],
         [ 1.6682e+00,  3.8106e+00],
         [ 1.2971e+00,  3.3655e+00],
         [ 2.7516e+00,  8.9503e-01],
         [ 3.7903e-01,  2.0646e+00],
         [ 1.5538e+00,  6.1068e-04],
         [ 1.4138e+00,  4.4610e-04],
         [ 1.3606e+00,  3.5574e-04],
         [-2.1766e-04,  1.0521e+00],
         [-1.8648e-01,  7.4002e-02],
         [ 6.4052e-03,  8.2327e-01],
         [ 5.3709e-01, -6.6224e-03],
         [ 1.2206e-01, -3.6177e-04],
         [ 8.3354e-03,  2.0148e-03],
         [-7.9482e-03,  3.2842e-03],
         [ 2.7683e-03, -1.8275e-03],
         [ 3.7495e+00,  1.5642e+00],
         [ 3.2628e+00,  1.2711e+00],
         [ 8.6096e-01,  2.7185e+00],
         [ 2.1068e+00,  4.5298e-01],
         [ 9.8820e-02,  8.7866e-01],
         [ 9.0883e-02,  6.4465e-01],
         [ 1.3081e+00,  5.2450e-04],
         [ 4.0494e-03,  1.1916e+00],
         [ 1.1356e+00,  1.3411e-03],
         [ 3.7871e-01,  3.2979e-03],
         [-1.1483e-03,  5.1682e-01],
         [ 2.6962e-06,  2.3083e-01],
         [ 3.1341e-03,  2.6291e-03],
         [ 7.3956e-03,  9.4125e-02],
         [-1.3743e-03, -3.3801e-04]]])

In [154]:
sigma

tensor([[[8.0229e+00, 9.6299e-01],
         [4.5377e-02, 7.4801e+00],
         [6.8625e+00, 2.4599e-02],
         [5.8585e+00, 2.4348e-02],
         [5.1200e+00, 1.9066e-02],
         [1.4414e-02, 4.4534e+00],
         [7.3694e-03, 3.7714e+00],
         [3.3498e+00, 1.0728e-02],
         [2.9087e+00, 7.1845e-03],
         [2.4733e+00, 6.3493e-03],
         [1.1250e-02, 1.4414e+00],
         [6.3019e-01, 1.4714e-02],
         [6.8038e-03, 5.1332e-01],
         [5.3516e-01, 1.7414e-02],
         [1.8202e-02, 9.8076e-03],
         [9.3135e-01, 7.8435e+00],
         [7.1425e+00, 4.8441e-02],
         [6.8961e+00, 3.1023e-02],
         [1.2889e-02, 6.0974e+00],
         [3.3172e-02, 5.7263e+00],
         [6.9585e-03, 4.6229e+00],
         [3.8838e+00, 8.9478e-03],
         [3.4042e+00, 8.7695e-03],
         [2.9659e+00, 1.1567e-02],
         [1.7918e+00, 9.5347e-03],
         [7.1653e-03, 2.0005e+00],
         [7.3563e-03, 2.8639e-01],
         [7.5145e-03, 7.5476e-01],
         [7.1783e-03, 3.1699e-01],
         [1.9371e-01, 5.8461e-03],
         [3.2837e+00, 1.5767e+00],
         [3.0773e+00, 1.3006e+00],
         [1.1663e+00, 2.7738e+00],
         [2.0755e+00, 3.5980e-02],
         [4.7651e-01, 1.7344e+00],
         [1.1283e-02, 1.4382e+00],
         [1.2878e+00, 8.2756e-03],
         [1.0815e+00, 9.4460e-03],
         [4.6151e-01, 9.1508e-03],
         [3.5509e-01, 1.1484e-02],
         [4.5052e-01, 8.9624e-03],
         [6.7388e-03, 6.2327e-01],
         [1.6032e-02, 3.2678e-02],
         [1.1977e-02, 3.6171e-02],
         [4.0906e-01, 6.6154e-03],
         [1.5810e+00, 3.4971e+00],
         [1.4830e+00, 3.3654e+00],
         [2.9322e+00, 1.2465e+00],
         [8.9135e-01, 2.3860e+00],
         [1.2495e-02, 1.7789e+00],
         [8.0200e-03, 1.5107e+00],
         [1.4377e+00, 6.2777e-03],
         [1.7539e-02, 7.3906e-01],
         [9.0350e-01, 7.2163e-03],
         [7.0159e-03, 8.9041e-01],
         [6.2913e-01, 6.1414e-03],
         [2.7309e-02, 3.6622e-02],
         [8.6961e-03, 1.1373e-01],
         [3.6461e-02, 7.0710e-03],
         [6.8063e-03, 1.8616e-01],
         [9.8733e-01, 4.3462e-02],
         [7.9651e-03, 1.1409e+00],
         [7.6172e-03, 9.9172e-01],
         [7.4707e-03, 9.1315e-01],
         [7.5305e-03, 8.7724e-01],
         [6.8040e-03, 8.0590e-01],
         [2.0397e-02, 8.1036e-01],
         [6.5946e-01, 6.7501e-03],
         [4.2971e-01, 1.0586e-02],
         [5.9072e-03, 7.7436e-01],
         [5.3577e-02, 2.9092e-02],
         [2.4382e-01, 7.1451e-03],
         [6.3786e-02, 9.8822e-03],
         [1.0909e-01, 3.3755e-02],
         [4.3632e-01, 9.1100e-03],
         [1.2411e+00, 8.4034e-03],
         [9.4103e-03, 1.1234e+00],
         [6.5132e-03, 1.1345e+00],
         [1.1945e+00, 9.4961e-03],
         [9.4136e-01, 8.9903e-03],
         [5.6157e-03, 7.9891e-01],
         [8.5621e-03, 8.0186e-01],
         [5.6047e-01, 1.6604e-02],
         [7.2548e-01, 7.0037e-03],
         [6.4069e-01, 7.3969e-03],
         [5.2713e-02, 1.1660e-02],
         [6.9854e-03, 1.6810e-01],
         [7.0851e-03, 2.5471e-01],
         [4.4593e-02, 1.0212e-02],
         [7.2445e-03, 2.2129e-01],
         [5.8662e-01, 1.1401e+00],
         [5.2366e-01, 1.0961e+00],
         [5.1015e-01, 1.0434e+00],
         [9.1535e-03, 8.0780e-01],
         [7.2355e-01, 8.4096e-03],
         [8.0576e-03, 7.0820e-01],
         [6.4903e-01, 8.9950e-03],
         [3.9725e-01, 1.9142e-02],
         [6.4387e-03, 6.5762e-01],
         [7.0319e-03, 5.5180e-01],
         [7.9041e-03, 4.7645e-01],
         [2.9057e-01, 1.0082e-02],
         [6.4625e-03, 1.4276e-01],
         [1.2187e-01, 7.8823e-03],
         [7.3372e-03, 6.9671e-01],
         [6.0331e-01, 1.2179e+00],
         [5.7327e-01, 1.1275e+00],
         [1.0629e+00, 5.2919e-01],
         [1.4384e-02, 9.6502e-01],
         [7.1480e-03, 7.8324e-01],
         [1.1980e-02, 7.1756e-01],
         [6.3583e-01, 7.8766e-03],
         [8.1166e-03, 5.6799e-01],
         [8.1325e-01, 7.3479e-03],
         [6.8511e-01, 7.1552e-03],
         [5.9835e-03, 4.9275e-01],
         [1.6188e-01, 1.0420e-02],
         [2.8659e-01, 8.4643e-03],
         [9.9981e-03, 1.3914e-01],
         [8.8073e-03, 1.5991e-01],
         [1.1038e+00, 1.7100e+00],
         [1.0223e+00, 1.7129e+00],
         [1.4976e+00, 8.0957e-01],
         [5.1753e-01, 1.1879e+00],
         [9.6407e-01, 8.8054e-03],
         [8.7632e-01, 1.1154e-02],
         [8.0186e-01, 8.5108e-03],
         [1.0217e-02, 6.0766e-01],
         [1.2865e-02, 4.1140e-01],
         [9.2957e-03, 7.9369e-01],
         [7.3895e-01, 6.2709e-03],
         [4.6645e-01, 5.6936e-03],
         [1.7538e-01, 7.9814e-03],
         [1.1202e-01, 6.8409e-03],
         [2.6511e-02, 2.4529e-02],
         [1.6960e+00, 1.1219e+00],
         [1.6214e+00, 9.9626e-01],
         [7.8375e-01, 1.4100e+00],
         [1.2325e+00, 5.5194e-01],
         [1.7259e-02, 1.0971e+00],
         [1.1852e-02, 9.1593e-01],
         [8.0594e-01, 6.6853e-03],
         [7.4031e-03, 7.2552e-01],
         [6.9296e-01, 8.5690e-03],
         [5.7487e-01, 7.3130e-03],
         [7.7015e-03, 7.4985e-01],
         [1.6548e-02, 7.6722e-02],
         [1.1705e-01, 6.2595e-03],
         [9.6648e-03, 2.3442e-01],
         [5.8423e-03, 4.0472e-01]]])

In [155]:
def sample_from_mdn(pi, mu, sigma):
    """
    pi:    (B, D, K) — mixture weights
    mu:    (B, D, K) — means
    sigma: (B, D, K) — stds

    Returns:
        samples: (B, D)
    """
    B, D, K = pi.shape

    # Step 1: Sample a component index from categorical distribution for each output dim
    categorical = torch.distributions.Categorical(pi)
    component_indices = categorical.sample()  # (B, D) — mixture component chosen per output

    # Step 2: Gather mu and sigma corresponding to sampled component
    batch_indices = torch.arange(B).unsqueeze(1).expand(B, D)  # (B, D)
    dim_indices = torch.arange(D).unsqueeze(0).expand(B, D)    # (B, D)

    # Gather the corresponding mu and sigma based on sampled component
    chosen_mu = mu[batch_indices, dim_indices, component_indices]
    chosen_sigma = sigma[batch_indices, dim_indices, component_indices]

    # Step 3: Sample from normal distribution
    normal = torch.distributions.Normal(chosen_mu, chosen_sigma)
    samples = normal.sample()  # (B, D)
    samples = torch.clamp(samples, min=0.0)

    return samples

In [156]:
samples = sample_from_mdn(pi, mu, sigma)  # Shape: (1, 360)

In [157]:
stats_df = players_and_stats(samples, GAME_ID, data)

     personId     points   assists    blocks    steals  rebounds
0   1628384.0   8.246575  6.225491  0.697726  0.238667  0.464307
1   1628973.0  12.079942  1.258709  0.002484  0.445299  0.830825
2   1630540.0  16.092461  4.199175  0.014264  1.182621  0.712251
3   1630173.0  10.541114  3.491971  0.000000  0.000000  0.043093
4   1630579.0   6.534563  4.256457  2.039735  0.001200  1.063739
5   1631210.0   9.806719  0.017984  0.009945  1.794422  1.662439
6         0.0   0.004320  1.307955  0.015809  0.000000  0.000000
7         0.0   0.006954  0.000000  0.012273  0.215655  0.007848
8         0.0   0.000000  0.000000  0.006588  0.007017  0.000000
9         0.0   0.001751  0.115898  0.004808  0.000000  0.015054
10        0.0   0.016154  0.000000  0.000000  0.005504  0.000000
11        0.0   0.011092  0.009601  0.004044  0.001528  0.000146
12        0.0   0.000000  0.000000  0.274719  0.016335  0.001718
13        0.0   0.000995  0.000000  0.001929  0.000000  0.007749
14        0.0   0.008490  0.000000  0.000000  0.005195  0.011136
15  1630162.0  12.925427  2.617606  0.000000  1.162837  1.947575
16  1630183.0   3.173097  5.847481  0.000000  0.182671  4.096814
17   203497.0  19.070364  1.384964  0.001081  3.557934  1.992090
18  1629638.0  10.472836  3.857360  0.000000  0.000000  1.481500
19   201144.0   8.779836  0.009564  0.001979  0.002210  0.000000
20  1629675.0   4.424425  0.022389  0.000000  0.010310  0.807456
21  1631169.0   0.000000  0.002342  0.000000  0.000000  2.046465
22        0.0   7.675921  0.106653  0.000000  0.000000  0.001995
23        0.0   0.000000  0.005161  0.010997  0.009919  0.643748
24        0.0   0.000694  0.004575  0.000000  0.000000  0.001886
25        0.0   0.006940  0.000000  0.000000  0.001387  0.000000
26        0.0   0.000000  0.022101  0.009718  0.008201  0.005463
27        0.0   0.000000  0.000000  0.000000  0.002541  0.005786
28        0.0   0.000000  0.003218  0.015815  0.013812  0.004200
29        0.0   0.000000  0.003259  0.010098  0.000000  0.000000

In [158]:
print(h["points"].sum(), a["points"].sum())

NameError: name 'h' is not defined

In [ ]:
h

shape: (15, 9)
┌───────────┬────────────┬──────────┬───────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ firstName ┆ lastName   ┆ personId ┆ points    ┆ … ┆ blocks   ┆ steals   ┆ reboundsTo ┆ turnovers │
│ ---       ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ tal        ┆ ---       │
│ str       ┆ str        ┆ i64      ┆ f32       ┆   ┆ f32      ┆ f32      ┆ ---        ┆ f32       │
│           ┆            ┆          ┆           ┆   ┆          ┆          ┆ f32        ┆           │
╞═══════════╪════════════╪══════════╪═══════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ Anthony   ┆ Edwards    ┆ 1630162  ┆ 25.803543 ┆ … ┆ 0.0      ┆ 0.947284 ┆ 9.076491   ┆ 1.751937  │
│ Julius    ┆ Randle     ┆ 203944   ┆ 39.267982 ┆ … ┆ 0.224781 ┆ 0.830468 ┆ 9.787584   ┆ 0.767914  │
│ Donte     ┆ DiVincenzo ┆ 1628978  ┆ 10.460669 ┆ … ┆ 0.0      ┆ 0.792567 ┆ 2.908532   ┆ 0.939958  │
│ Jaden     ┆ McDaniels  ┆ 1630183  ┆ 6.931751  ┆ … ┆ 0.010324 ┆ 0.0      ┆ 11.6703    ┆ 2.813545  │
│ Rudy      ┆ Gobert     ┆ 203497   ┆ 11.035434 ┆ … ┆ 0.003017 ┆ 2.051392 ┆ 4.685094   ┆ 4.405427  │
│ …         ┆ …          ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ Luka      ┆ Garza      ┆ 1630568  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.014725   ┆ 0.0       │
│ Josh      ┆ Minott     ┆ 1631169  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.007492 ┆ 0.0        ┆ 0.0       │
│ PJ        ┆ Dozier     ┆ 1628408  ┆ 0.003239  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.004313  │
│ null      ┆ null       ┆ null     ┆ 0.000559  ┆ … ┆ 0.018026 ┆ 0.0      ┆ 0.001782   ┆ 0.0       │
│ null      ┆ null       ┆ null     ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.000343 ┆ 0.0        ┆ 0.000011  │
└───────────┴────────────┴──────────┴───────────┴───┴──────────┴──────────┴────────────┴───────────┘

In [ ]:
a

shape: (15, 9)
┌─────────────┬──────────┬──────────┬───────────┬───┬──────────┬──────────┬────────────┬───────────┐
│ firstName   ┆ lastName ┆ personId ┆ points    ┆ … ┆ blocks   ┆ steals   ┆ reboundsTo ┆ turnovers │
│ ---         ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ tal        ┆ ---       │
│ str         ┆ str      ┆ i64      ┆ f32       ┆   ┆ f32      ┆ f32      ┆ ---        ┆ f32       │
│             ┆          ┆          ┆           ┆   ┆          ┆          ┆ f32        ┆           │
╞═════════════╪══════════╪══════════╪═══════════╪═══╪══════════╪══════════╪════════════╪═══════════╡
│ Karl-Anthon ┆ Towns    ┆ 1626157  ┆ 24.767124 ┆ … ┆ 0.02243  ┆ 0.0      ┆ 3.038804   ┆ 0.856735  │
│ y           ┆          ┆          ┆           ┆   ┆          ┆          ┆            ┆           │
│ Mikal       ┆ Bridges  ┆ 1628969  ┆ 14.453997 ┆ … ┆ 2.606043 ┆ 0.728308 ┆ 10.440793  ┆ 9.481155  │
│ OG          ┆ Anunoby  ┆ 1628384  ┆ 27.45118  ┆ … ┆ 0.00204  ┆ 2.314866 ┆ 10.908648  ┆ 1.49482   │
│ Jalen       ┆ Brunson  ┆ 1628973  ┆ 24.209377 ┆ … ┆ 1.022304 ┆ 0.003147 ┆ 8.669761   ┆ 1.406437  │
│ Miles       ┆ McBride  ┆ 1630540  ┆ 8.667492  ┆ … ┆ 0.001319 ┆ 0.577933 ┆ 14.273738  ┆ 1.795496  │
│ …           ┆ …        ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …          ┆ …         │
│ Ariel       ┆ Hukporti ┆ 1630574  ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.013652 ┆ 0.003178   ┆ 0.0       │
│ Tyler       ┆ Kolek    ┆ 1642278  ┆ 0.000803  ┆ … ┆ 0.0      ┆ 0.001046 ┆ 0.0        ┆ 0.0       │
│ Jacob       ┆ Toppin   ┆ 1631210  ┆ 0.003803  ┆ … ┆ 0.003229 ┆ 0.0      ┆ 0.00247    ┆ 0.008193  │
│ null        ┆ null     ┆ null     ┆ 0.010089  ┆ … ┆ 0.0      ┆ 0.0      ┆ 0.0        ┆ 0.0       │
│ null        ┆ null     ┆ null     ┆ 0.0       ┆ … ┆ 0.0      ┆ 0.001736 ┆ 0.0        ┆ 0.004337  │
└─────────────┴──────────┴──────────┴───────────┴───┴──────────┴──────────┴────────────┴───────────┘